# Generated by Django 5.2.7 on 2026-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_manual_override',
            field=models.BooleanField(default=False, help_text='Can seller apply manual price override'),
        ),
    ]
