# Generated by Django 5.2.7 on 2026-02-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_allow_manual_override'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allow_manual_override',
            new_name='allow_manual_price',
        ),
    ]
