# docker-compose.yml
# NOTE: omit explicit 'version' (Compose v2/v3 compatibility); keep services only.
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tutorlix/frontend:local
    container_name: tutorlix-repo-frontend-1
    restart: unless-stopped
    ports:
      - "10001:10001"
    environment:
      NODE_ENV: production
    depends_on:
      - bff
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:10001/ || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - tutorlix_net

networks:
  tutorlix_net:
    driver: bridge

volumes:
  static_data:
  media_data:
