# Generated by Django 5.2.7 on 2025-10-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespecificclass',
            name='main_course',
        ),
        migrations.AlterModelOptions(
            name='coursespecificclass',
            options={'ordering': ['product', 'name'], 'verbose_name': 'Course Specific Class', 'verbose_name_plural': 'Course Specific Classes'},
        ),
        migrations.AddField(
            model_name='coursespecificclass',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='lms.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MainCourse',
        ),
    ]
