# Generated by Django 5.2.7 on 2026-01-13 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_remove_attendance_students_attendance_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='coursebooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursebooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursebooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
