# Generated by Django 5.2.7 on 2026-01-13 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_coursebooking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
