# Generated by Django 5.2.7 on 2026-01-13 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_coursebooking_booking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, help_text='Reason for the expense', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='Select the seller who received this money', limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_expenses_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Expense',
                'verbose_name_plural': 'Seller Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
