# Generated by Django 5.2.7 on 2026-01-18 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_sellerexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, help_text='JSON structure containing modules and lessons'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of course features/highlights'),
        ),
        migrations.AddField(
            model_name='product',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(blank=True, help_text='Full HTML/Rich text content for the course overview tab'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Short description for cards/previews'),
        ),
    ]
