# Generated by Django 5.2.7 on 2026-01-19 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_product_curriculum_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration_days',
            field=models.IntegerField(blank=True, default=30, help_text='Duration in days. Leave 0 or empty for lifetime access.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
