# Generated by Django 5.2.7 on 2026-01-20 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_product_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespecificclass',
            name='time',
        ),
        migrations.AddField(
            model_name='coursespecificclass',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Class End Time'),
        ),
        migrations.AddField(
            model_name='coursespecificclass',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Class Start Time'),
        ),
    ]
