# Generated by Django 5.2.7 on 2026-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_coursespecificclass_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profileTypes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('AB', 'Absent'), ('Partial', 'Partial')], default='AB', max_length=10),
        ),
    ]
