# Generated by Django 5.2.7 on 2026-01-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_productlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lms.product'),
        ),
        migrations.AlterField(
            model_name='productlead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
