# Generated by Django 5.2.7 on 2026-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_productlead_product_alter_productlead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlead',
            name='source',
            field=models.CharField(default='Course Page', max_length=50),
        ),
    ]
