# Generated by Django 5.2.7 on 2026-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_productlead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
