# Generated by Django 5.2.7 on 2026-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_product_manual_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='manual_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
