# Generated by Django 5.2.7 on 2026-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_coursebooking_manual_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlead',
            name='interest_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
