# Generated by Django 5.2.7 on 2026-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_productlead_interest_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
