# Generated by Django 5.2.7 on 2026-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_coursebooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='payment_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
