# Generated by Django 5.2.7 on 2026-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_masterclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='masterclasses/'),
        ),
    ]
