# Generated by Django 5.2.7 on 2026-02-08 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_alter_paymenthistory_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='course_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
