# Generated by Django 5.2.7 on 2026-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_masterclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='teacher',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
