# Generated by Django 5.2.7 on 2026-04-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_question_bank_data(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankTopic = apps.get_model('lms', 'QuestionBankTopic')
    QuestionBankQuestion = apps.get_model('lms', 'QuestionBankQuestion')

    course_payloads = [
        {
            'title': 'IB Mathematics grade 2 for class 11',
            'slug': 'ib-mathematics-grade-2-class-11',
            'subject': 'Mathematics',
            'grade_label': 'Grade 2',
            'class_label': 'Class 11',
            'description': 'IB Mathematics question bank organized by official syllabus topics for a more analytical pathway.',
            'syllabus_label': 'IB Mathematics: analysis and approaches SL-aligned topic structure',
            'syllabus_source_url': 'https://www.ibo.org/globalassets/new-structure/university-admission/pdfs/subject-guides/mathematics-analysis-approaches-guide.pdf',
            'topics': [
                {
                    'title': 'Number and Algebra',
                    'slug': 'number-and-algebra',
                    'summary': 'Sequences, series, algebraic manipulation, and numerical methods from the official syllabus structure.',
                    'order': 1,
                    'questions': [
                        {
                            'question': 'The fourth term of an arithmetic sequence is 10 and the ninth term is 25. Find the first term and the common difference.',
                            'answer': 'Use a + 3d = 10 and a + 8d = 25. Subtract to get 5d = 15, so d = 3. Substitute back: a + 9 = 10, so a = 1.',
                            'order': 1,
                            'source_label': 'Save My Exams - Arithmetic Sequences & Series',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/hl/revision-notes/number-and-algebra/sequences-and-series/arithmetic/',
                        },
                        {
                            'question': 'The sum of the first 10 terms of an arithmetic sequence is 630. If the first term is 18, find the common difference.',
                            'answer': 'Apply S_n = n/2 [2a + (n - 1)d]. With 630 = 10/2 [36 + 9d], we get 630 = 180 + 45d, so d = 10.',
                            'order': 2,
                            'source_label': 'Save My Exams - Arithmetic Sequences & Series',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/hl/revision-notes/number-and-algebra/sequences-and-series/arithmetic/',
                        },
                    ],
                },
                {
                    'title': 'Functions',
                    'slug': 'functions',
                    'summary': 'Representation, transformation, and interpretation of functions, including quadratic behavior.',
                    'order': 2,
                    'questions': [
                        {
                            'question': 'Write x^2 + 6x + 5 in completed-square form and state its minimum value.',
                            'answer': 'x^2 + 6x + 5 = (x + 3)^2 - 4. Since (x + 3)^2 is at least 0, the minimum value is -4 at x = -3.',
                            'order': 1,
                            'source_label': 'Save My Exams - Completing the Square',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/sl/revision-notes/functions/quadratic-functions-and-graphs/completing-the-square/',
                        },
                    ],
                },
                {
                    'title': 'Geometry and Trigonometry',
                    'slug': 'geometry-and-trigonometry',
                    'summary': 'Shape, measurement, trigonometric relationships, and geometric modelling from the IB topic framework.',
                    'order': 3,
                    'questions': [],
                },
                {
                    'title': 'Probability and Statistics',
                    'slug': 'probability-and-statistics',
                    'summary': 'Probability distributions, expected value, and interpretation of statistical results.',
                    'order': 4,
                    'questions': [
                        {
                            'question': 'A game costs $15 to play. The prizes are $1, $5, $10 and $100 with probabilities 0.35, 0.5, 0.05 and 0.1 respectively. Find the expected prize and decide whether the game is fair.',
                            'answer': 'Expected prize = 1(0.35) + 5(0.5) + 10(0.05) + 100(0.1) = 13.35. Expected gain after paying is 13.35 - 15 = -1.65, so the game is not fair for the player.',
                            'order': 1,
                            'source_label': 'Save My Exams - Expected Values',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/sl/revision-notes/statistics-and-probability/probability-distributions/expected-values/',
                        },
                    ],
                },
                {
                    'title': 'Calculus',
                    'slug': 'calculus',
                    'summary': 'Rates of change, limits, and calculus modelling from the official topic outline.',
                    'order': 5,
                    'questions': [],
                },
            ],
        },
        {
            'title': 'IB Mathematics grade 1 for class 11',
            'slug': 'ib-mathematics-grade-1-class-11',
            'subject': 'Mathematics',
            'grade_label': 'Grade 1',
            'class_label': 'Class 11',
            'description': 'IB Mathematics question bank organized by official syllabus topics for an applications-focused pathway.',
            'syllabus_label': 'IB Mathematics: applications and interpretation SL-aligned topic structure',
            'syllabus_source_url': 'https://www.ibo.org/globalassets/new-structure/university-admission/pdfs/dp-mathematics-applications-and-interpretation-guide-en.pdf',
            'topics': [
                {
                    'title': 'Number and Algebra',
                    'slug': 'number-and-algebra',
                    'summary': 'Sequences, finance-style arithmetic, and algebraic forms from the official syllabus structure.',
                    'order': 1,
                    'questions': [
                        {
                            'question': 'An arithmetic sequence has first term 7 and common difference 4. Find the 12th term.',
                            'answer': 'Use u_n = a + (n - 1)d. So u_12 = 7 + 11(4) = 51.',
                            'order': 1,
                            'source_label': 'Save My Exams - Arithmetic Sequences & Series',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/hl/revision-notes/number-and-algebra/sequences-and-series/arithmetic/',
                        },
                        {
                            'question': 'The sum of the first 10 terms of an arithmetic sequence is 630. If the common difference is 11, find the first term.',
                            'answer': 'Use 630 = 10/2 [2a + 9(11)]. This gives 630 = 5(2a + 99), so 126 = 2a + 99 and a = 13.5.',
                            'order': 2,
                            'source_label': 'Save My Exams - Arithmetic Sequences & Series',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/hl/revision-notes/number-and-algebra/sequences-and-series/arithmetic/',
                        },
                    ],
                },
                {
                    'title': 'Functions',
                    'slug': 'functions',
                    'summary': 'Quadratic and other functional models used to interpret patterns and relationships.',
                    'order': 2,
                    'questions': [
                        {
                            'question': 'For the quadratic y = x^2 - 4x + 3, find the x-intercepts and the vertex.',
                            'answer': 'Factor to get (x - 1)(x - 3) = 0, so the x-intercepts are x = 1 and x = 3. Complete the square: y = (x - 2)^2 - 1, so the vertex is (2, -1).',
                            'order': 1,
                            'source_label': 'Save My Exams - Quadratic Functions',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/sl/revision-notes/functions/quadratic-functions-and-graphs/quadratic-functions/',
                        },
                    ],
                },
                {
                    'title': 'Geometry and Trigonometry',
                    'slug': 'geometry-and-trigonometry',
                    'summary': 'Measurement, visualization, and trigonometric interpretation within the official topic framework.',
                    'order': 3,
                    'questions': [],
                },
                {
                    'title': 'Probability and Statistics',
                    'slug': 'probability-and-statistics',
                    'summary': 'Probability models, distributions, and statistical interpretation from the IB applications pathway.',
                    'order': 4,
                    'questions': [
                        {
                            'question': 'A random variable X takes values 2, 4, and 10 with probabilities 0.2, 0.5, and 0.3. Find E(X).',
                            'answer': 'E(X) = 2(0.2) + 4(0.5) + 10(0.3) = 0.4 + 2 + 3 = 5.4.',
                            'order': 1,
                            'source_label': 'Save My Exams - Expected Values',
                            'source_url': 'https://www.savemyexams.com/dp/maths/ib/aa/21/sl/revision-notes/statistics-and-probability/probability-distributions/expected-values/',
                        },
                    ],
                },
                {
                    'title': 'Calculus',
                    'slug': 'calculus',
                    'summary': 'Introductory calculus ideas within the official topic outline.',
                    'order': 5,
                    'questions': [],
                },
            ],
        },
    ]

    for course_data in course_payloads:
        topics_data = course_data.pop('topics')
        course, _ = QuestionBankCourse.objects.update_or_create(
            slug=course_data['slug'],
            defaults=course_data,
        )

        for topic_data in topics_data:
            questions_data = topic_data.pop('questions')
            topic, _ = QuestionBankTopic.objects.update_or_create(
                course=course,
                slug=topic_data['slug'],
                defaults=topic_data,
            )

            for question_data in questions_data:
                QuestionBankQuestion.objects.update_or_create(
                    topic=topic,
                    order=question_data['order'],
                    defaults=question_data,
                )


def unseed_question_bank_data(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankCourse.objects.filter(
        slug__in=[
            'ib-mathematics-grade-2-class-11',
            'ib-mathematics-grade-1-class-11',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0023_alter_masterclass_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subject', models.CharField(default='Mathematics', max_length=100)),
                ('grade_label', models.CharField(max_length=100)),
                ('class_label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('syllabus_label', models.CharField(blank=True, max_length=255, null=True)),
                ('syllabus_source_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Bank Course',
                'verbose_name_plural': 'Question Bank Courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lms.questionbankcourse')),
            ],
            options={
                'verbose_name': 'Question Bank Topic',
                'verbose_name_plural': 'Question Bank Topics',
                'ordering': ['order', 'title'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source_label', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.questionbanktopic')),
            ],
            options={
                'verbose_name': 'Question Bank Question',
                'verbose_name_plural': 'Question Bank Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_question_bank_data, unseed_question_bank_data),
    ]
