# Generated by Django 5.2.7 on 2026-02-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_alter_coursebooking_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_bookings', to='lms.product'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_histories', to='lms.product'),
        ),
    ]
