# Generated by Django 5.2.7 on 2026-02-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_coursebooking_course_name_and_more'),
    ]

    operations = [
    ]
