# Generated by Django 5.2.7 on 2026-04-16

from django.db import migrations


def add_more_question_bank_content(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankTopic = apps.get_model('lms', 'QuestionBankTopic')
    QuestionBankQuestion = apps.get_model('lms', 'QuestionBankQuestion')

    payload = {
        'ib-mathematics-grade-2-class-11': {
            'number-and-algebra': [
                {
                    'order': 3,
                    'question': 'The first term of a geometric sequence is 5 and the common ratio is 2. Find the sixth term.',
                    'answer': 'Use u_n = ar^(n-1). So u_6 = 5 x 2^5 = 160.',
                    'source_label': 'IB-style geometric sequence practice',
                },
            ],
            'functions': [
                {
                    'order': 2,
                    'question': 'Find the axis of symmetry and roots of y = x^2 - 8x + 12.',
                    'answer': 'The axis of symmetry is x = -b/2a = 8/2 = 4. Factor: x^2 - 8x + 12 = (x - 2)(x - 6), so the roots are x = 2 and x = 6.',
                    'source_label': 'IB-style quadratic functions practice',
                },
            ],
            'geometry-and-trigonometry': [
                {
                    'order': 1,
                    'question': 'In a right triangle, one acute angle is 35 degrees and the hypotenuse is 10 cm. Find the side opposite the 35 degree angle.',
                    'answer': 'Use sine: opposite / 10 = sin(35°). So opposite = 10 sin(35°) ≈ 5.74 cm.',
                    'source_label': 'IB-style trigonometry practice',
                },
            ],
            'probability-and-statistics': [
                {
                    'order': 2,
                    'question': 'A discrete random variable X takes values 1, 3 and 5 with probabilities 0.2, 0.5 and 0.3. Find E(X).',
                    'answer': 'E(X) = 1(0.2) + 3(0.5) + 5(0.3) = 0.2 + 1.5 + 1.5 = 3.2.',
                    'source_label': 'IB-style expected value practice',
                },
            ],
            'calculus': [
                {
                    'order': 1,
                    'question': 'Differentiate f(x) = 3x^2 - 4x + 7.',
                    'answer': 'f\'(x) = 6x - 4.',
                    'source_label': 'IB-style calculus practice',
                },
            ],
        },
        'ib-mathematics-grade-1-class-11': {
            'number-and-algebra': [
                {
                    'order': 3,
                    'question': 'Simplify 3(2x - 5) + 4(x + 1).',
                    'answer': 'Expand and combine like terms: 6x - 15 + 4x + 4 = 10x - 11.',
                    'source_label': 'IB-style algebra practice',
                },
            ],
            'functions': [
                {
                    'order': 2,
                    'question': 'For f(x) = 2x + 1, find f(4) and the inverse function.',
                    'answer': 'f(4) = 2(4) + 1 = 9. To find the inverse, write y = 2x + 1, swap x and y: x = 2y + 1, so y = (x - 1)/2. Therefore f^-1(x) = (x - 1)/2.',
                    'source_label': 'IB-style linear functions practice',
                },
            ],
            'geometry-and-trigonometry': [
                {
                    'order': 1,
                    'question': 'A circle has radius 7 cm. Find its area in terms of pi.',
                    'answer': 'Area = pi r^2 = pi x 7^2 = 49pi cm^2.',
                    'source_label': 'IB-style geometry practice',
                },
            ],
            'probability-and-statistics': [
                {
                    'order': 2,
                    'question': 'A fair six-sided die is rolled once. What is the probability of getting a prime number?',
                    'answer': 'The prime outcomes are 2, 3 and 5, so there are 3 favorable outcomes out of 6. Probability = 3/6 = 1/2.',
                    'source_label': 'IB-style probability practice',
                },
            ],
            'calculus': [
                {
                    'order': 1,
                    'question': 'Find the gradient of y = x^2 at x = 3.',
                    'answer': 'Differentiate to get dy/dx = 2x. At x = 3, the gradient is 2(3) = 6.',
                    'source_label': 'IB-style introductory calculus practice',
                },
            ],
        },
    }

    for course_slug, topic_map in payload.items():
        try:
            course = QuestionBankCourse.objects.get(slug=course_slug)
        except QuestionBankCourse.DoesNotExist:
            continue

        for topic_slug, questions in topic_map.items():
            try:
                topic = QuestionBankTopic.objects.get(course=course, slug=topic_slug)
            except QuestionBankTopic.DoesNotExist:
                continue

            for item in questions:
                QuestionBankQuestion.objects.update_or_create(
                    topic=topic,
                    order=item['order'],
                    defaults={
                        'question': item['question'],
                        'answer': item['answer'],
                        'source_label': item.get('source_label'),
                        'source_url': item.get('source_url'),
                        'is_active': True,
                    },
                )


def remove_more_question_bank_content(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankTopic = apps.get_model('lms', 'QuestionBankTopic')
    QuestionBankQuestion = apps.get_model('lms', 'QuestionBankQuestion')

    removal_map = {
        'ib-mathematics-grade-2-class-11': {
            'number-and-algebra': [3],
            'functions': [2],
            'geometry-and-trigonometry': [1],
            'probability-and-statistics': [2],
            'calculus': [1],
        },
        'ib-mathematics-grade-1-class-11': {
            'number-and-algebra': [3],
            'functions': [2],
            'geometry-and-trigonometry': [1],
            'probability-and-statistics': [2],
            'calculus': [1],
        },
    }

    for course_slug, topic_map in removal_map.items():
        try:
            course = QuestionBankCourse.objects.get(slug=course_slug)
        except QuestionBankCourse.DoesNotExist:
            continue

        for topic_slug, orders in topic_map.items():
            try:
                topic = QuestionBankTopic.objects.get(course=course, slug=topic_slug)
            except QuestionBankTopic.DoesNotExist:
                continue

            QuestionBankQuestion.objects.filter(topic=topic, order__in=orders).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_question_bank_models'),
    ]

    operations = [
        migrations.RunPython(add_more_question_bank_content, remove_more_question_bank_content),
    ]
