# Generated by Django 5.2.7 on 2026-04-16

from django.db import migrations
import math


QUESTION_COUNT_PER_TOPIC = 100
SOURCE_LABEL = "Tutorlix generated practice bank"


def format_number(value):
    if isinstance(value, float):
        rounded = round(value, 2)
        if rounded.is_integer():
            return str(int(rounded))
        return f"{rounded:.2f}".rstrip("0").rstrip(".")
    return str(value)


def get_level_factor(course_slug):
    return 2 if "grade-2" in course_slug else 1


def generate_number_algebra(course_slug, index):
    level = get_level_factor(course_slug)
    variant = (index - 1) % 5
    seed = index + level * 10

    if variant == 0:
        a = 3 + seed
        d = 2 + (seed % 7)
        n = 4 + (seed % 8)
        answer = a + (n - 1) * d
        question = f"An arithmetic sequence has first term {a} and common difference {d}. Find the {n}th term."
        solution = f"Use u_n = a + (n - 1)d. So u_{n} = {a} + {n - 1}({d}) = {answer}."
    elif variant == 1:
        a = 2 + (seed % 6)
        r = 2 + (seed % 3)
        n = 3 + (seed % 5)
        answer = a * (r ** (n - 1))
        question = f"A geometric sequence has first term {a} and common ratio {r}. Find the {n}th term."
        solution = f"Use u_n = ar^(n-1). So u_{n} = {a} x {r}^{n - 1} = {answer}."
    elif variant == 2:
        x = 2 + seed
        coeff = 2 + (seed % 5)
        constant = 3 + (seed % 9)
        rhs = coeff * x + constant
        question = f"Solve the linear equation {coeff}x + {constant} = {rhs}."
        solution = f"Subtract {constant} from both sides to get {coeff}x = {rhs - constant}. Then divide by {coeff}: x = {x}."
    elif variant == 3:
        base = 2 + (seed % 5)
        p = 2 + (seed % 4)
        q = 3 + (seed % 5)
        r = 1 + (seed % 3)
        exponent = p + q - r
        question = f"Simplify {base}^{p} x {base}^{q} / {base}^{r}."
        solution = f"Add exponents when multiplying and subtract when dividing: {p} + {q} - {r} = {exponent}. So the result is {base}^{exponent}."
    else:
        a = 4 + seed
        d = 1 + (seed % 6)
        n = 5 + (seed % 7)
        answer = n * (2 * a + (n - 1) * d) / 2
        question = f"Find the sum of the first {n} terms of an arithmetic sequence with first term {a} and common difference {d}."
        solution = f"Use S_n = n/2 [2a + (n - 1)d]. So S_{n} = {n}/2 [2({a}) + {n - 1}({d})] = {format_number(answer)}."

    return question, solution


def generate_functions(course_slug, index):
    level = get_level_factor(course_slug)
    variant = (index - 1) % 5
    seed = index + level * 8

    if variant == 0:
        a = 2 + (seed % 5)
        b = 1 + seed
        x_value = 2 + (seed % 6)
        answer = a * x_value + b
        question = f"For f(x) = {a}x + {b}, find f({x_value})."
        solution = f"Substitute x = {x_value}: f({x_value}) = {a}({x_value}) + {b} = {answer}."
    elif variant == 1:
        a = 2 + (seed % 4)
        b = 1 + (seed % 9)
        question = f"Find the inverse of f(x) = {a}x + {b}."
        solution = f"Let y = {a}x + {b}. Swap x and y: x = {a}y + {b}. Then y = (x - {b})/{a}. So f^-1(x) = (x - {b})/{a}."
    elif variant == 2:
        p = 1 + (seed % 6)
        q = p + 2 + (seed % 4)
        question = f"Find the roots of y = x^2 - {p + q}x + {p * q}."
        solution = f"Factor the quadratic: x^2 - {p + q}x + {p * q} = (x - {p})(x - {q}). The roots are x = {p} and x = {q}."
    elif variant == 3:
        h = 1 + (seed % 6)
        k = -(2 + (seed % 5))
        constant = h * h + k
        question = f"Find the vertex of y = x^2 - {2 * h}x + {constant}."
        solution = f"Complete the square: y = (x - {h})^2 {k}. So the vertex is ({h}, {k})."
    else:
        h = 2 + (seed % 5)
        value = -(3 + (seed % 4))
        constant = h * h + value
        question = f"Write y = x^2 - {2 * h}x + {constant} in completed-square form."
        solution = f"y = (x - {h})^2 {value}. The completed-square form is y = (x - {h})^2 {value}."

    return question, solution


def generate_geometry_trig(course_slug, index):
    level = get_level_factor(course_slug)
    variant = (index - 1) % 5
    seed = index + level * 6

    if variant == 0:
        radius = 3 + seed
        question = f"A circle has radius {radius} cm. Find its area in terms of pi."
        solution = f"Area = pi r^2 = pi x {radius}^2 = {radius * radius}pi cm^2."
    elif variant == 1:
        a = 3 + (seed % 8)
        b = 4 + (seed % 7)
        hyp = math.sqrt(a * a + b * b)
        question = f"A right triangle has perpendicular sides {a} cm and {b} cm. Find the hypotenuse."
        solution = f"Use Pythagoras: c = sqrt({a}^2 + {b}^2) = sqrt({a * a + b * b}) = {format_number(hyp)} cm."
    elif variant == 2:
        hyp = 8 + seed
        angle = 20 + (seed % 35)
        opposite = hyp * math.sin(math.radians(angle))
        question = f"In a right triangle, one acute angle is {angle} degrees and the hypotenuse is {hyp} cm. Find the side opposite the angle."
        solution = f"Use sin(theta) = opposite / hypotenuse. So opposite = {hyp} sin({angle}°) ≈ {format_number(opposite)} cm."
    elif variant == 3:
        radius = 5 + seed
        circumference = 2 * math.pi * radius
        question = f"A circle has radius {radius} cm. Find its circumference in terms of pi and as a decimal."
        solution = f"Circumference = 2pi r = 2pi({radius}) = {2 * radius}pi cm ≈ {format_number(circumference)} cm."
    else:
        opposite = 3 + (seed % 10)
        adjacent = 4 + (seed % 9)
        angle = math.degrees(math.atan(opposite / adjacent))
        question = f"A right triangle has opposite side {opposite} cm and adjacent side {adjacent} cm. Find the angle theta."
        solution = f"tan(theta) = {opposite}/{adjacent}. So theta = tan^-1({opposite}/{adjacent}) ≈ {format_number(angle)}°."

    return question, solution


def generate_probability_statistics(course_slug, index):
    level = get_level_factor(course_slug)
    variant = (index - 1) % 5
    seed = index + level * 12

    if variant == 0:
        x1 = 1 + (seed % 4)
        x2 = x1 + 2
        x3 = x2 + 3
        p1 = 0.2
        p2 = 0.5
        p3 = 0.3
        expected = x1 * p1 + x2 * p2 + x3 * p3
        question = f"A random variable X takes values {x1}, {x2}, and {x3} with probabilities 0.2, 0.5, and 0.3. Find E(X)."
        solution = f"E(X) = {x1}(0.2) + {x2}(0.5) + {x3}(0.3) = {format_number(expected)}."
    elif variant == 1:
        values = [seed, seed + 2, seed + 4, seed + 6, seed + 8]
        mean = sum(values) / len(values)
        question = f"Find the mean of the data set: {', '.join(str(v) for v in values)}."
        solution = f"Add the values and divide by 5: ({' + '.join(str(v) for v in values)}) / 5 = {format_number(mean)}."
    elif variant == 2:
        sides = 6 + (seed % 5)
        primes = len([n for n in range(1, sides + 1) if n > 1 and all(n % d for d in range(2, int(math.sqrt(n)) + 1))])
        question = f"A fair {sides}-sided die numbered 1 to {sides} is rolled once. What is the probability of getting a prime number?"
        solution = f"There are {primes} prime outcomes out of {sides}. Probability = {primes}/{sides}."
    elif variant == 3:
        values = [seed - 1, seed, seed + 2, seed + 4, seed + 5]
        median = values[len(values) // 2]
        question = f"Find the median of the ordered data set: {', '.join(str(v) for v in values)}."
        solution = f"There are 5 values, so the median is the middle value. The median is {median}."
    else:
        red = 3 + (seed % 5)
        blue = 4 + (seed % 6)
        probability = red / (red + blue)
        question = f"A bag contains {red} red balls and {blue} blue balls. One ball is chosen at random. Find the probability that it is red."
        solution = f"Probability(red) = favorable / total = {red} / ({red} + {blue}) = {red}/{red + blue} = {format_number(probability)}."

    return question, solution


def generate_calculus(course_slug, index):
    level = get_level_factor(course_slug)
    variant = (index - 1) % 5
    seed = index + level * 9

    if variant == 0:
        a = 2 + (seed % 6)
        b = 1 + (seed % 7)
        c = 3 + (seed % 8)
        question = f"Differentiate f(x) = {a}x^2 + {b}x + {c}."
        solution = f"Using the power rule, f'(x) = {2 * a}x + {b}."
    elif variant == 1:
        a = 1 + (seed % 5)
        b = 2 + (seed % 6)
        x_value = 1 + (seed % 7)
        gradient = 2 * a * x_value + b
        question = f"Find the gradient of y = {a}x^2 + {b}x + 1 at x = {x_value}."
        solution = f"Differentiate to get dy/dx = {2 * a}x + {b}. At x = {x_value}, the gradient is {2 * a}({x_value}) + {b} = {gradient}."
    elif variant == 2:
        a = 1 + (seed % 4)
        b = 1 + (seed % 5)
        x_value = 2 + (seed % 4)
        y_value = a * x_value * x_value + b
        gradient = 2 * a * x_value
        intercept = y_value - gradient * x_value
        question = f"Find the equation of the tangent to y = {a}x^2 + {b} at x = {x_value}."
        solution = f"At x = {x_value}, y = {y_value}. The derivative is dy/dx = {2 * a}x, so the gradient is {gradient}. Using y = mx + c through ({x_value}, {y_value}), c = {intercept}. The tangent is y = {gradient}x + {intercept}."
    elif variant == 3:
        a = 1 + (seed % 3)
        b = 2 + (seed % 4)
        question = f"Differentiate f(x) = {a}x^3 - {b}x^2 + 4."
        solution = f"Using the power rule, f'(x) = {3 * a}x^2 - {2 * b}x."
    else:
        h = 2 + (seed % 6)
        question = f"Find the stationary point of y = x^2 - {2 * h}x + 5."
        solution = f"Differentiate: dy/dx = 2x - {2 * h}. Set equal to zero: 2x - {2 * h} = 0, so x = {h}. Substitute back: y = {h * h - 2 * h * h + 5}. The stationary point is ({h}, {h * h - 2 * h * h + 5})."

    return question, solution


GENERATOR_MAP = {
    "number-and-algebra": generate_number_algebra,
    "functions": generate_functions,
    "geometry-and-trigonometry": generate_geometry_trig,
    "probability-and-statistics": generate_probability_statistics,
    "calculus": generate_calculus,
}


def seed_100_questions_per_topic(apps, schema_editor):
    QuestionBankCourse = apps.get_model("lms", "QuestionBankCourse")
    QuestionBankTopic = apps.get_model("lms", "QuestionBankTopic")
    QuestionBankQuestion = apps.get_model("lms", "QuestionBankQuestion")

    supported_course_slugs = [
        "ib-mathematics-grade-1-class-11",
        "ib-mathematics-grade-2-class-11",
    ]

    for course in QuestionBankCourse.objects.filter(slug__in=supported_course_slugs):
        for topic in QuestionBankTopic.objects.filter(course=course):
            generator = GENERATOR_MAP.get(topic.slug)
            if not generator:
                continue

            for order in range(1, QUESTION_COUNT_PER_TOPIC + 1):
                question_text, answer_text = generator(course.slug, order)
                QuestionBankQuestion.objects.update_or_create(
                    topic=topic,
                    order=order,
                    defaults={
                        "question": question_text,
                        "answer": answer_text,
                        "source_label": SOURCE_LABEL,
                        "source_url": "",
                        "is_active": True,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0025_expand_question_bank_content"),
    ]

    operations = [
        migrations.RunPython(seed_100_questions_per_topic, migrations.RunPython.noop),
    ]
