# Generated by Django 5.2.7 on 2026-02-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_backfill_paymenthistory_course'),
    ]

    operations = [
    ]
