# Generated by Django 5.2.7 on 2026-04-16

from django.db import migrations, models


def seed_profile_types(apps, schema_editor):
    ProfileType = apps.get_model('lms', 'ProfileType')
    payload = [
        {
            'slug': 'school',
            'title': 'School Student',
            'description': 'Learn basics and build a strong foundation.',
            'order': 1,
            'is_active': True,
        },
        {
            'slug': 'college',
            'title': 'College Student',
            'description': 'Upskill and prepare for your career.',
            'order': 2,
            'is_active': True,
        },
        {
            'slug': 'professional',
            'title': 'IT Professional',
            'description': 'Advance your skills and switch roles faster.',
            'order': 3,
            'is_active': True,
        },
    ]

    for item in payload:
        ProfileType.objects.update_or_create(slug=item['slug'], defaults=item)


def unseed_profile_types(apps, schema_editor):
    ProfileType = apps.get_model('lms', 'ProfileType')
    ProfileType.objects.filter(slug__in=['school', 'college', 'professional']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_seed_100_questions_per_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Type',
                'verbose_name_plural': 'Profile Types',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RunPython(seed_profile_types, unseed_profile_types),
    ]
