# Generated by Django 5.2.7 on 2026-04-16

from django.db import migrations, models


QUESTION_COUNT_PER_TOPIC = 100
SOURCE_LABEL = "Tutorlix generated practice bank"


def dsa_question(topic_slug, index):
    if topic_slug == 'arrays-and-hashing':
        question = f"DSA Arrays Question {index}: Given an array of integers, describe how you would detect duplicates efficiently."
        answer = f"Use a hash set while iterating through the array. For question {index}, the efficient approach is O(n) time with O(n) extra space because each element is checked once against the set."
    elif topic_slug == 'linked-lists':
        question = f"DSA Linked List Question {index}: Explain how to reverse a singly linked list iteratively."
        answer = f"Maintain prev, current, and next pointers. For question {index}, move through the list once, redirect current.next to prev, then advance all pointers. This is O(n) time and O(1) space."
    elif topic_slug == 'stacks-and-queues':
        question = f"DSA Stack and Queue Question {index}: How would you validate balanced parentheses in a string?"
        answer = f"Push opening brackets onto a stack and pop when a matching closing bracket appears. For question {index}, if a mismatch occurs or the stack is non-empty at the end, the string is invalid."
    elif topic_slug == 'trees-and-graphs':
        question = f"DSA Trees and Graphs Question {index}: When would you choose BFS over DFS in graph traversal?"
        answer = f"For question {index}, BFS is preferred when the shortest path in an unweighted graph is needed or when level-order traversal matters, while DFS is better for exhaustive search and recursion-friendly exploration."
    else:
        question = f"DSA Dynamic Programming Question {index}: What is the core idea behind dynamic programming?"
        answer = f"For question {index}, dynamic programming solves overlapping subproblems once, stores their results, and reuses them to build the final answer through memoization or tabulation."
    return question, answer


def system_design_question(topic_slug, index):
    if topic_slug == 'scalability-fundamentals':
        question = f"System Design Scalability Question {index}: What is horizontal scaling and why is it useful?"
        answer = f"For question {index}, horizontal scaling means adding more machines instead of making a single machine larger. It improves capacity, availability, and fault tolerance for growing systems."
    elif topic_slug == 'databases-and-storage':
        question = f"System Design Database Question {index}: When would you choose sharding for a database?"
        answer = f"For question {index}, sharding is useful when a single database node cannot handle write throughput or data volume. It partitions data across multiple nodes to distribute load."
    elif topic_slug == 'caching-and-queues':
        question = f"System Design Cache Question {index}: Why is caching introduced in high-traffic systems?"
        answer = f"For question {index}, caching reduces repeated expensive reads, lowers latency, and decreases load on the database by serving frequently accessed data from a faster layer."
    elif topic_slug == 'load-balancing-and-networking':
        question = f"System Design Networking Question {index}: What problem does a load balancer solve?"
        answer = f"For question {index}, a load balancer distributes incoming traffic across multiple servers so no single server becomes a bottleneck, improving both availability and performance."
    else:
        question = f"System Design Reliability Question {index}: Why are monitoring and observability critical in production systems?"
        answer = f"For question {index}, monitoring and observability help detect failures quickly, understand system behavior, debug incidents, and measure whether reliability targets are being met."
    return question, answer


def seed_question_bank_profiles_and_cs_content(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankTopic = apps.get_model('lms', 'QuestionBankTopic')
    QuestionBankQuestion = apps.get_model('lms', 'QuestionBankQuestion')

    QuestionBankCourse.objects.filter(
        slug__in=[
            'ib-mathematics-grade-1-class-11',
            'ib-mathematics-grade-2-class-11',
        ]
    ).update(profileTypes=['school'])

    course_payloads = [
        {
            'slug': 'dsa',
            'title': 'DSA',
            'subject': 'Computer Science',
            'profileTypes': ['college', 'professional'],
            'grade_label': 'Core',
            'class_label': 'Interview Prep',
            'description': 'Data structures and algorithms question bank for college learners and IT professionals.',
            'syllabus_label': 'Tutorlix DSA topic structure',
            'syllabus_source_url': '',
            'topics': [
                ('arrays-and-hashing', 'Arrays and Hashing', 'Core array operations, hashing patterns, and lookup optimization.'),
                ('linked-lists', 'Linked Lists', 'Pointer manipulation, traversal, and linked-list transformations.'),
                ('stacks-and-queues', 'Stacks and Queues', 'LIFO/FIFO structures, parsing, and processing flows.'),
                ('trees-and-graphs', 'Trees and Graphs', 'Traversal, connectivity, recursion, and search strategies.'),
                ('dynamic-programming', 'Dynamic Programming', 'Subproblem reuse, state modeling, and optimization patterns.'),
            ],
            'generator': dsa_question,
        },
        {
            'slug': 'system-design',
            'title': 'System Design',
            'subject': 'Computer Science',
            'profileTypes': ['college', 'professional'],
            'grade_label': 'Advanced',
            'class_label': 'Architecture',
            'description': 'System design question bank covering scalable architecture and production tradeoffs.',
            'syllabus_label': 'Tutorlix System Design topic structure',
            'syllabus_source_url': '',
            'topics': [
                ('scalability-fundamentals', 'Scalability Fundamentals', 'Traffic growth, scaling strategies, and architecture basics.'),
                ('databases-and-storage', 'Databases and Storage', 'Persistence, partitioning, consistency, and storage tradeoffs.'),
                ('caching-and-queues', 'Caching and Queues', 'Latency reduction, asynchronous processing, and decoupling.'),
                ('load-balancing-and-networking', 'Load Balancing and Networking', 'Traffic distribution, gateways, and network edge concerns.'),
                ('reliability-and-observability', 'Reliability and Observability', 'Monitoring, resilience, failure handling, and operational insight.'),
            ],
            'generator': system_design_question,
        },
    ]

    for course_data in course_payloads:
        topics = course_data.pop('topics')
        generator = course_data.pop('generator')
        course, _ = QuestionBankCourse.objects.update_or_create(
            slug=course_data['slug'],
            defaults=course_data,
        )

        for order, (topic_slug, topic_title, topic_summary) in enumerate(topics, start=1):
            topic, _ = QuestionBankTopic.objects.update_or_create(
                course=course,
                slug=topic_slug,
                defaults={
                    'title': topic_title,
                    'summary': topic_summary,
                    'order': order,
                    'is_active': True,
                },
            )

            for question_order in range(1, QUESTION_COUNT_PER_TOPIC + 1):
                question_text, answer_text = generator(topic_slug, question_order)
                QuestionBankQuestion.objects.update_or_create(
                    topic=topic,
                    order=question_order,
                    defaults={
                        'question': question_text,
                        'answer': answer_text,
                        'source_label': SOURCE_LABEL,
                        'source_url': '',
                        'is_active': True,
                    },
                )


def unseed_question_bank_profiles_and_cs_content(apps, schema_editor):
    QuestionBankCourse = apps.get_model('lms', 'QuestionBankCourse')
    QuestionBankCourse.objects.filter(slug__in=['dsa', 'system-design']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankcourse',
            name='profileTypes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_question_bank_profiles_and_cs_content, unseed_question_bank_profiles_and_cs_content),
    ]
