# Generated by Django 5.2.7 on 2026-04-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_refresh_cs_question_bank_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('tone', models.CharField(default='Friendly', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('avatar_style', models.CharField(default='Young Indian female tutor avatar', max_length=255)),
                ('board_style', models.CharField(default='Modern digital smart board', max_length=255)),
                ('voice_style', models.CharField(default='Warm teacher voice', max_length=255)),
                ('call_to_action', models.CharField(blank=True, max_length=255, null=True)),
                ('include_instagram_post', models.BooleanField(default=False)),
                ('instagram_caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('script_text', models.TextField(blank=True, null=True)),
                ('scene_plan', models.JSONField(blank=True, default=list)),
                ('board_notes', models.JSONField(blank=True, default=list)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready For Review'), ('queued_to_publish', 'Queued To Publish'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('provider_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('ready', 'Ready'), ('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_configured', max_length=30)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('render_preview_url', models.URLField(blank=True, null=True)),
                ('instagram_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_permalink', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reel Generation Job',
                'verbose_name_plural': 'Reel Generation Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
