# Generated by Django 5.2.7 on 2026-04-18

from django.db import migrations, models


DEFAULT_HOME_CONTENT = {
    'school': {
        'navigation': {
            'primary_links': [
                {'label': 'Home', 'url': '/', 'visibility': 'public'},
                {'label': 'Live Classes', 'url': '/courses', 'visibility': 'public'},
                {'label': 'Question Banks', 'url': '/question-banks', 'visibility': 'public'},
                {'label': 'Notes', 'url': '/notes', 'visibility': 'public'},
                {'label': 'Masterclass', 'url': '/masterclass', 'visibility': 'public'},
                {'label': 'Contact', 'url': '/contact', 'visibility': 'public'},
            ],
            'question_banks_label': 'Question Banks',
            'question_banks_url': '/question-banks',
            'tutorials_enabled': True,
            'tutorials_heading': 'Core Topics (All Courses)',
            'tutorials_description': 'All IB Math courses cover these five areas, though depth differs.',
        },
        'hero': {
            'tag': 'For School Students',
            'headline': 'Online maths tutoring for IB MYP, IBDP Maths, IGCSE Maths, AP Calculus AB/BC, AP Precalculus, Algebra 2, Geometry, Algebra 1, and SAT Maths.',
            'bullets': [
                'Concept clarity with expert teachers',
                'Maths & science made easy',
                'Learn at your own pace',
            ],
            'quick_programs': [
                'IB MYP',
                'IBDP Maths',
                'IGCSE Maths',
                'AP Calculus AB/BC',
                'SAT Maths',
            ],
            'stats': [
                {'value': '1:1', 'label': 'Online classes'},
                {'value': 'Live', 'label': 'Doubt solving'},
                {'value': 'Exam', 'label': 'Focused plans'},
            ],
            'cta': 'Get Academic Guidance',
            'lead_title': 'Start your journey',
            'lead_success_title': 'Sent!',
            'lead_success_cta': 'Send another',
        },
        'benefits': {
            'title': 'Why students love Tutorlix',
            'subtitle': 'Strong concepts, clear basics, and learning made fun.',
            'items': [
                {'icon': 'book-open', 'title': 'Concept Clarity', 'description': 'Simple explanations that build strong foundations.'},
                {'icon': 'users', 'title': 'Expert Teachers', 'description': 'Learn from experienced teachers.'},
                {'icon': 'target', 'title': 'Step-by-Step Learning', 'description': 'Structured learning for school success.'},
            ],
        },
        'about': {
            'badge': 'About Tutorlix',
            'title': 'Interactive learning that\nactually works.',
            'description': 'Take your math and computer science skills to the next level with Tutorlix. Say goodbye to boring lectures and hello to hands-on lessons and exciting projects.',
            'cards': [
                {'icon': 'target', 'title': 'Fortnightly Testing', 'description': 'Track progress with challenging tests designed to apply your problem-solving skills.'},
                {'icon': 'brain-circuit', 'title': 'High-Quality Content', 'description': 'Well-recorded lectures and dynamic resources ensure an informative experience.'},
            ],
            'image_url': 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
            'quote': 'Education is not the filling of a pail, but the lighting of a fire.',
            'quote_author': 'W.B. Yeats',
        },
        'testimonials': {
            'title': 'Student Success Stories',
            'subtitle': "Don't just take our word for it. Hear from our community.",
            'items': [
                {'name': 'Diya Shukla', 'course': 'Maths for BE, BTech, BBA and BCA', 'text': 'Maths became simple and interesting.'},
                {'name': 'B. Jahnavi', 'course': 'JEE Maths (One Year)', 'text': 'Teaching style is very clear.'},
                {'name': 'Vinod Kumar', 'course': 'Front End Development', 'text': 'Every doubt is cleared properly.'},
            ],
        },
        'tutorials': [
            {
                'slug': 'number-and-algebra',
                'title': 'Number and Algebra',
                'shortDescription': 'Sequences, series, logarithms, and binomial expansion.',
                'overview': 'This tutorial builds the algebraic foundation used across IB Mathematics. It starts with number patterns and sequences, moves through series and logarithmic relationships, and then connects those ideas to binomial expansion and algebraic manipulation.',
                'learnPoints': [
                    'Work confidently with arithmetic and geometric sequences and series.',
                    'Understand logarithmic laws and how logarithms model inverse exponential behavior.',
                    'Apply binomial expansion accurately and recognize when approximations are useful.',
                    'Build the algebra fluency needed for functions, calculus, and probability.',
                ],
                'scopeLabel': 'Core Topics (All Courses)',
            },
            {
                'slug': 'functions',
                'title': 'Functions',
                'shortDescription': 'Graphing, transformations, and specific types like exponential and logarithmic functions.',
                'overview': 'This tutorial explains how functions describe relationships between variables and how those relationships appear visually on graphs. It covers graphing techniques, transformations, and the behavior of important function families including exponential and logarithmic models.',
                'learnPoints': [
                    'Interpret domain, range, intercepts, and key features from function graphs.',
                    'Apply translations, reflections, stretches, and other transformations cleanly.',
                    'Compare linear, quadratic, exponential, and logarithmic functions.',
                    'Use function notation and modeling to solve contextual problems.',
                ],
                'scopeLabel': 'Core Topics (All Courses)',
            },
            {
                'slug': 'geometry-and-trigonometry',
                'title': 'Geometry and Trigonometry',
                'shortDescription': '2D and 3D geometry, trigonometric functions, and identities.',
                'overview': 'This tutorial focuses on shape, space, angle, and periodic relationships. Students work through geometric reasoning in two and three dimensions and then connect that reasoning to trigonometric functions, equations, and identities.',
                'learnPoints': [
                    'Solve problems involving angles, lengths, areas, and volumes in 2D and 3D settings.',
                    'Understand sine, cosine, and tangent as functions, not just ratios.',
                    'Use trigonometric identities and equations in structured problem solving.',
                    'Read and interpret trigonometric graphs with confidence.',
                ],
                'scopeLabel': 'Core Topics (All Courses)',
            },
            {
                'slug': 'statistics-and-probability',
                'title': 'Statistics and Probability',
                'shortDescription': 'Data analysis, probability distributions, and correlation.',
                'overview': 'This tutorial develops statistical reasoning from data collection through interpretation. It covers descriptive statistics, probability models, distributions, and correlation so students can explain trends and make mathematically sound conclusions.',
                'learnPoints': [
                    'Summarize and interpret data using tables, diagrams, and numerical measures.',
                    'Work with probability rules and common distributions in a structured way.',
                    'Understand correlation, regression, and the limits of statistical conclusions.',
                    'Translate real data into mathematical language and justified interpretations.',
                ],
                'scopeLabel': 'Core Topics (All Courses)',
            },
            {
                'slug': 'calculus',
                'title': 'Calculus',
                'shortDescription': 'Differentiation and integration techniques.',
                'overview': 'This tutorial introduces change and accumulation through differentiation and integration. It covers core techniques, graph interpretation, and practical applications so students can move from formulas to reasoning about rates and areas.',
                'learnPoints': [
                    'Differentiate common function types and interpret derivatives graphically.',
                    'Use integration to recover quantities and calculate area-related results.',
                    'Connect calculus methods to motion, optimization, and modeling problems.',
                    'Build technique alongside conceptual understanding for exam questions.',
                ],
                'scopeLabel': 'Core Topics (All Courses)',
            },
        ],
    },
    'college': {
        'navigation': {
            'primary_links': [
                {'label': 'Home', 'url': '/', 'visibility': 'public'},
                {'label': 'Live Classes', 'url': '/courses', 'visibility': 'public'},
                {'label': 'Question Banks', 'url': '/question-banks', 'visibility': 'public'},
                {'label': 'Notes', 'url': '/notes', 'visibility': 'public'},
                {'label': 'Masterclass', 'url': '/masterclass', 'visibility': 'public'},
                {'label': 'Contact', 'url': '/contact', 'visibility': 'public'},
            ],
            'question_banks_label': 'Question Banks',
            'question_banks_url': '/question-banks',
            'tutorials_enabled': True,
            'tutorials_heading': 'Career-Ready Topic Tracks',
            'tutorials_description': 'These tutorials help college students build stronger coding, project, placement, and engineering fundamentals.',
        },
        'hero': {
            'tag': 'For College Students',
            'headline': 'Become job-ready\nbefore graduation.',
            'bullets': [
                'Industry-aligned curriculum',
                'Internship & placement support',
                'Hands-on project learning',
            ],
            'quick_programs': [
                'Full Stack Dev',
                'Data Science & AI',
                'DSA',
                'Placement Prep',
                'System Design Basics',
            ],
            'stats': [
                {'value': 'Projects', 'label': 'Portfolio building'},
                {'value': 'Mentors', 'label': 'Career guidance'},
                {'value': 'Jobs', 'label': 'Placement focus'},
            ],
            'cta': 'Get Career Guidance',
            'lead_title': 'Start your journey',
            'lead_success_title': 'Sent!',
            'lead_success_cta': 'Send another',
        },
        'benefits': {
            'title': 'Why college students choose us',
            'subtitle': 'Learn skills that actually matter in the real world.',
            'items': [
                {'icon': 'rocket', 'title': 'Industry-Oriented Learning', 'description': 'Curriculum aligned with placements.'},
                {'icon': 'code-2', 'title': 'Hands-on Projects', 'description': 'Build real projects for your portfolio.'},
                {'icon': 'users', 'title': 'Mentorship Support', 'description': 'Guidance from senior mentors.'},
            ],
        },
        'about': {
            'badge': 'About Tutorlix',
            'title': 'Interactive learning that\nactually works.',
            'description': 'Take your math and computer science skills to the next level with Tutorlix. Say goodbye to boring lectures and hello to hands-on lessons and exciting projects.',
            'cards': [
                {'icon': 'target', 'title': 'Fortnightly Testing', 'description': 'Track progress with challenging tests designed to apply your problem-solving skills.'},
                {'icon': 'brain-circuit', 'title': 'High-Quality Content', 'description': 'Well-recorded lectures and dynamic resources ensure an informative experience.'},
            ],
            'image_url': 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
            'quote': 'Education is not the filling of a pail, but the lighting of a fire.',
            'quote_author': 'W.B. Yeats',
        },
        'testimonials': {
            'title': 'Student Success Stories',
            'subtitle': "Don't just take our word for it. Hear from our community.",
            'items': [
                {'name': 'Diya Shukla', 'course': 'Maths for BE, BTech, BBA and BCA', 'text': 'Maths became simple and interesting.'},
                {'name': 'B. Jahnavi', 'course': 'JEE Maths (One Year)', 'text': 'Teaching style is very clear.'},
                {'name': 'Vinod Kumar', 'course': 'Front End Development', 'text': 'Every doubt is cleared properly.'},
            ],
        },
        'tutorials': [
            {
                'slug': 'data-structures-and-algorithms',
                'title': 'Data Structures & Algorithms',
                'shortDescription': 'Arrays, linked lists, trees, graphs, recursion, and problem-solving patterns.',
                'overview': 'This tutorial track builds the core programming problem-solving ability expected in college placements and software internships. It covers fundamental data structures, algorithm analysis, and the practical thinking patterns needed to solve coding interview questions with clarity.',
                'learnPoints': [
                    'Choose the right data structure for search, update, traversal, and storage tasks.',
                    'Understand time and space complexity and use them to compare solutions.',
                    'Apply recursion, dynamic programming, greedy methods, and graph traversal patterns.',
                    'Translate abstract algorithmic thinking into clean, testable code.',
                ],
                'scopeLabel': 'Career Core',
            },
            {
                'slug': 'web-development',
                'title': 'Web Development',
                'shortDescription': 'Frontend fundamentals, APIs, full-stack architecture, and deployment basics.',
                'overview': 'This tutorial introduces the complete web development journey from browser-side interfaces to backend services. It is designed for college students who need practical project-building ability, not just syntax familiarity.',
                'learnPoints': [
                    'Build responsive frontend interfaces with modern component-based thinking.',
                    'Understand how APIs, routing, authentication, and databases work together.',
                    'Develop project structure discipline for scalable full-stack applications.',
                    'Move from small assignments to portfolio-quality web products.',
                ],
                'scopeLabel': 'Career Core',
            },
            {
                'slug': 'database-systems',
                'title': 'Database Systems',
                'shortDescription': 'SQL design, normalization, querying, indexing, and transaction basics.',
                'overview': 'This tutorial helps students move beyond basic table queries and understand how data systems are actually modeled and queried in production applications. It covers relational thinking, query optimization basics, and practical data design habits.',
                'learnPoints': [
                    'Design structured schemas with cleaner normalization decisions.',
                    'Write joins, aggregations, subqueries, and filters confidently.',
                    'Understand indexes, constraints, and transaction concepts at a practical level.',
                    'Connect database choices to application performance and maintainability.',
                ],
                'scopeLabel': 'Career Core',
            },
            {
                'slug': 'aptitude-and-problem-solving',
                'title': 'Aptitude & Problem Solving',
                'shortDescription': 'Quantitative aptitude, logical reasoning, and campus placement problem solving.',
                'overview': 'This tutorial sharpens the analytical skills frequently tested in campus hiring rounds. It combines speed, structured reasoning, and accuracy so students can perform better in placement preparation alongside technical study.',
                'learnPoints': [
                    'Break down quantitative questions into repeatable reasoning frameworks.',
                    'Improve speed and accuracy on common aptitude problem types.',
                    'Recognize logical traps and solve reasoning questions systematically.',
                    'Prepare with a stronger balance of technical and non-technical readiness.',
                ],
                'scopeLabel': 'Placement Prep',
            },
            {
                'slug': 'system-design-foundations',
                'title': 'System Design Foundations',
                'shortDescription': 'Scalability basics, architecture thinking, and backend design tradeoffs.',
                'overview': 'This tutorial introduces architecture-level thinking in a beginner-friendly way for college students preparing for advanced internships or full-time roles. It focuses on conceptual clarity rather than senior-level depth.',
                'learnPoints': [
                    'Understand clients, servers, databases, caching, queues, and APIs as system parts.',
                    'Reason about scale, reliability, latency, and availability tradeoffs.',
                    'Explain architecture choices in interviews and project reviews more clearly.',
                    'Build a strong bridge from coding skills to engineering design thinking.',
                ],
                'scopeLabel': 'Advanced Prep',
            },
        ],
    },
    'professional': {
        'navigation': {
            'primary_links': [
                {'label': 'Home', 'url': '/', 'visibility': 'public'},
                {'label': 'Live Classes', 'url': '/courses', 'visibility': 'public'},
                {'label': 'Question Banks', 'url': '/question-banks', 'visibility': 'public'},
                {'label': 'Notes', 'url': '/notes', 'visibility': 'public'},
                {'label': 'Masterclass', 'url': '/masterclass', 'visibility': 'public'},
                {'label': 'Contact', 'url': '/contact', 'visibility': 'public'},
            ],
            'question_banks_label': 'Question Banks',
            'question_banks_url': '/question-banks',
            'tutorials_enabled': True,
            'tutorials_heading': 'Professional Growth Tracks',
            'tutorials_description': 'These tutorials focus on advanced engineering depth, delivery skills, and career progression for working professionals.',
        },
        'hero': {
            'tag': 'For Working Professionals',
            'headline': 'Switch or grow your\ntech career faster.',
            'bullets': [
                'Upskill with real-world projects',
                'Mentorship from senior engineers',
                'Designed for busy professionals',
            ],
            'quick_programs': [
                'System Design',
                'Cloud & DevOps',
                'Backend Engineering',
                'Interview Prep',
                'AI for Engineers',
            ],
            'stats': [
                {'value': 'Flexible', 'label': 'Weekend-friendly'},
                {'value': 'Senior', 'label': 'Mentor support'},
                {'value': 'Career', 'label': 'Switch plans'},
            ],
            'cta': 'Get Upskilling Plan',
            'lead_title': 'Start your journey',
            'lead_success_title': 'Sent!',
            'lead_success_cta': 'Send another',
        },
        'benefits': {
            'title': 'Why professionals trust Tutorlix',
            'subtitle': 'Upskill faster and move ahead in your career.',
            'items': [
                {'icon': 'rocket', 'title': 'Career Acceleration', 'description': 'Designed for career switch and growth.'},
                {'icon': 'brain-circuit', 'title': 'Advanced Skill Paths', 'description': 'Modern stacks used in real companies.'},
                {'icon': 'users', 'title': '1:1 Mentorship', 'description': 'Solve real-world problems with experts.'},
            ],
        },
        'about': {
            'badge': 'About Tutorlix',
            'title': 'Interactive learning that\nactually works.',
            'description': 'Take your math and computer science skills to the next level with Tutorlix. Say goodbye to boring lectures and hello to hands-on lessons and exciting projects.',
            'cards': [
                {'icon': 'target', 'title': 'Fortnightly Testing', 'description': 'Track progress with challenging tests designed to apply your problem-solving skills.'},
                {'icon': 'brain-circuit', 'title': 'High-Quality Content', 'description': 'Well-recorded lectures and dynamic resources ensure an informative experience.'},
            ],
            'image_url': 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop',
            'quote': 'Education is not the filling of a pail, but the lighting of a fire.',
            'quote_author': 'W.B. Yeats',
        },
        'testimonials': {
            'title': 'Student Success Stories',
            'subtitle': "Don't just take our word for it. Hear from our community.",
            'items': [
                {'name': 'Diya Shukla', 'course': 'Maths for BE, BTech, BBA and BCA', 'text': 'Maths became simple and interesting.'},
                {'name': 'B. Jahnavi', 'course': 'JEE Maths (One Year)', 'text': 'Teaching style is very clear.'},
                {'name': 'Vinod Kumar', 'course': 'Front End Development', 'text': 'Every doubt is cleared properly.'},
            ],
        },
        'tutorials': [
            {
                'slug': 'system-design',
                'title': 'System Design',
                'shortDescription': 'Scalable services, architecture tradeoffs, availability, and performance design.',
                'overview': 'This tutorial is aimed at working professionals who need stronger architecture depth for senior interviews, team leadership, or backend-heavy roles. It covers distributed system building blocks and the reasoning behind production tradeoffs.',
                'learnPoints': [
                    'Design systems using caching, queues, databases, and service boundaries intentionally.',
                    'Evaluate latency, consistency, reliability, and scaling tradeoffs in realistic scenarios.',
                    'Communicate architecture decisions with more precision in interviews and design discussions.',
                    'Move from feature implementation thinking to system-level engineering judgment.',
                ],
                'scopeLabel': 'Professional Track',
            },
            {
                'slug': 'cloud-and-devops',
                'title': 'Cloud & DevOps',
                'shortDescription': 'CI/CD, containers, deployment pipelines, observability, and cloud fundamentals.',
                'overview': 'This tutorial helps professionals strengthen modern delivery and infrastructure skills. It focuses on the operational side of engineering, including deployments, automation, reliability, and practical cloud-native workflows.',
                'learnPoints': [
                    'Understand deployment pipelines and how to reduce release friction safely.',
                    'Work confidently with containers, environments, and cloud service building blocks.',
                    'Improve monitoring, logging, and observability for production systems.',
                    'Connect infrastructure decisions to team velocity and service reliability.',
                ],
                'scopeLabel': 'Professional Track',
            },
            {
                'slug': 'backend-architecture',
                'title': 'Backend Architecture',
                'shortDescription': 'Service boundaries, APIs, data flow, resilience, and maintainable backend design.',
                'overview': 'This tutorial focuses on engineering backend systems that remain understandable and maintainable as teams and products grow. It is useful for professionals moving into stronger ownership roles or scaling beyond CRUD-heavy applications.',
                'learnPoints': [
                    'Design cleaner service contracts and backend boundaries.',
                    'Handle failures, retries, idempotency, and asynchronous workflows more deliberately.',
                    'Reduce complexity by structuring backend code and data flows with stronger patterns.',
                    'Think in terms of maintainability, not just immediate delivery speed.',
                ],
                'scopeLabel': 'Professional Track',
            },
            {
                'slug': 'ai-engineering',
                'title': 'AI Engineering',
                'shortDescription': 'LLM workflows, prompt systems, evaluation, and product integration basics.',
                'overview': 'This tutorial is for professionals who want to move from curiosity about AI to practical implementation skills. It focuses on integrating modern AI capabilities into real applications with attention to reliability, UX, and evaluation.',
                'learnPoints': [
                    'Understand where AI fits well in real product and automation workflows.',
                    'Work with prompts, structured outputs, retrieval, and evaluation loops effectively.',
                    'Recognize tradeoffs around hallucinations, cost, latency, and safety.',
                    'Build more realistic AI features instead of demo-only prototypes.',
                ],
                'scopeLabel': 'Professional Track',
            },
            {
                'slug': 'technical-interview-strategy',
                'title': 'Technical Interview Strategy',
                'shortDescription': 'Interview storytelling, senior-level problem framing, and role transition preparation.',
                'overview': 'This tutorial helps experienced engineers prepare for role changes, promotions, and interview processes where communication matters as much as raw coding. It blends technical clarity with professional positioning.',
                'learnPoints': [
                    'Explain past projects and ownership decisions in a stronger interview narrative.',
                    'Frame tradeoffs and architecture reasoning in a senior-friendly way.',
                    'Prepare for coding, design, and behavioral rounds as one coherent story.',
                    'Present depth, judgment, and impact more effectively during transitions.',
                ],
                'scopeLabel': 'Career Growth',
            },
        ],
    },
}


def seed_home_content(apps, schema_editor):
    ProfileType = apps.get_model('lms', 'ProfileType')

    for slug, content in DEFAULT_HOME_CONTENT.items():
        ProfileType.objects.filter(slug=slug).update(home_content=content)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_reelgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='home_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_home_content, migrations.RunPython.noop),
    ]
