# Generated by Django 5.2.7 on 2026-04-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_test_grading_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='forumcomment',
            new_name='lms_forumco_post_id_81a008_idx',
            old_name='lms_forumco_post_id_342a08_idx',
        ),
        migrations.RenameIndex(
            model_name='forumcomment',
            new_name='lms_forumco_author__e4f25e_idx',
            old_name='lms_forumco_author__972e07_idx',
        ),
        migrations.RenameIndex(
            model_name='forumcomment',
            new_name='lms_forumco_is_acti_8578ca_idx',
            old_name='lms_forumco_is_acti_131cd0_idx',
        ),
        migrations.RenameIndex(
            model_name='forumnotification',
            new_name='lms_forumno_recipie_35f2c3_idx',
            old_name='lms_forumno_recipie_9644ca_idx',
        ),
        migrations.RenameIndex(
            model_name='forumnotification',
            new_name='lms_forumno_recipie_c08a6f_idx',
            old_name='lms_forumno_recipie_5eb5f8_idx',
        ),
        migrations.RenameIndex(
            model_name='forumnotification',
            new_name='lms_forumno_notific_5bfe16_idx',
            old_name='lms_forumno_notific_19b4df_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpost',
            new_name='lms_forumpo_is_acti_98b79d_idx',
            old_name='lms_forumpo_is_acti_8f6c88_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpost',
            new_name='lms_forumpo_author__71c56c_idx',
            old_name='lms_forumpo_author__c44085_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpostlike',
            new_name='lms_forumpo_post_id_ca3279_idx',
            old_name='lms_forumpo_post_id_eec2fd_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpostlike',
            new_name='lms_forumpo_user_id_015b35_idx',
            old_name='lms_forumpo_user_id_477063_idx',
        ),
    ]
