# Generated by Django 5.2.7 on 2026-04-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_alter_resource_file'),
        ('lms', '0039_resource_import_fields_and_approved_domain'),
    ]

    operations = [
    ]
