# Generated by Django 5.2.7 on 2026-04-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_merge_20260425_0002'),
        ('lms', '0040_resourceimportjob'),
    ]

    operations = [
    ]
