# Generated by Django 5.2.7 on 2026-04-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_merge_0040_merge_20260425_0002_0040_resourceimportjob'),
        ('lms', '0041_resourceimportjob_aborted_status'),
    ]

    operations = [
    ]
