# Generated by Django 5.2.7 on 2026-04-26 18:09

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0042_merge_20260425_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/apple/tutorlix_next/backend/protected_resources')), upload_to='resources/%Y/%m/'),
        ),
    ]
