apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: backend-prod
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      containers:
        - name: backend-prod
          image: ankitvashishta7/tutorlix-backend-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          volumeMounts:
            - name: db-storage
              mountPath: /app/db.sqlite3

      volumes:
        - name: db-storage
          hostPath:
            path: /var/www/tutorlix-prod/backend/db.sqlite3
            type: FileOrCreate   # 👈 FIX
---
apiVersion: v1
kind: Service
metadata:
  name: backend-prod
spec:
  type: NodePort
  selector:
    app: backend-prod
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31235

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-prod
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      containers:
        - name: frontend-prod
          image: ankitvashishta7/tutorlix-frontend-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-prod-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
spec:
  type: NodePort
  selector:
    app: frontend-prod
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31568

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'backend-prod'
        static_configs:
          - targets: ['backend-prod:8000']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
  
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true   # 👈 ADD THIS
      containers:
        - name: node-exporter
          image: prom/node-exporter
          args:
            - "--path.rootfs=/host"
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100