# Generated by Django 5.2.7 on 2026-02-07 13:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0017_productlead_interest_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='BlockNote editor content as JSON')),
                ('note_type', models.CharField(choices=[('paid', 'Paid Note'), ('course_specific', 'Course Specific'), ('public', 'Public')], default='public', max_length=20)),
                ('privacy', models.CharField(choices=[('logged_in', 'Logged In Users Only'), ('course_specific', 'Course Specific Only'), ('purchase_only', 'Purchase Only')], default='logged_in', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('access_duration_days', models.IntegerField(default=0, help_text='Duration in days after purchase. 0 = lifetime access.', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Short description for preview/listing')),
                ('is_draft', models.BooleanField(default=True, help_text='Auto-save draft feature')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Link to product/course for course-specific notes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload image or PDF', upload_to='notes/attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document')], default='image', max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original price at time of purchase', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount paid', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('access_valid_until', models.DateTimeField(blank=True, help_text='When the access expires (null = lifetime)', null=True)),
                ('purchased_by', models.CharField(blank=True, help_text='Name of sales rep or system (for admin-created purchases)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='notes.note')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='note_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('purchase', 'Via Purchase'), ('course_booking', 'Via Course Booking'), ('manual', 'Manual Grant by Admin')], default='manual', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When access expires (null = lifetime)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_booking', models.ForeignKey(blank=True, help_text="Link to course booking if access_type is 'course_booking'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_accesses', to='lms.coursebooking')),
                ('granted_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_note_accesses', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='notes.note')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='note_accesses', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, help_text="Link to purchase if access_type is 'purchase'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='notes.notepurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type', 'is_active'], name='notes_note_note_ty_7b67ae_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['creator', 'is_draft'], name='notes_note_creator_bddaef_idx'),
        ),
        migrations.AddIndex(
            model_name='notepurchase',
            index=models.Index(fields=['student', 'payment_status'], name='notes_notep_student_2a0a92_idx'),
        ),
        migrations.AddIndex(
            model_name='notepurchase',
            index=models.Index(fields=['note', 'payment_status'], name='notes_notep_note_id_6ed190_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notepurchase',
            unique_together={('student', 'note')},
        ),
        migrations.AddIndex(
            model_name='noteaccess',
            index=models.Index(fields=['student', 'is_active'], name='notes_notea_student_839e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='noteaccess',
            index=models.Index(fields=['note', 'is_active'], name='notes_notea_note_id_39aab6_idx'),
        ),
    ]
