# Generated by Django 5.2.7 on 2026-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('course_specific', 'Course Specific'), ('individual', 'Individual')], default='individual', help_text='Course Specific: tied to a product. Individual: privacy field applies.', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged In Users Only'), ('purchaseable', 'Purchaseable')], default='logged_in', help_text='Only applies to individual notes. Ignored for course-specific notes.', max_length=20),
        ),
        migrations.AlterField(
            model_name='noteaccess',
            name='access_type',
            field=models.CharField(choices=[('purchase', 'Via Purchase'), ('course_booking', 'Via Course Booking'), ('manual', 'Manual Grant by Admin'), ('free_enrollment', 'Free Enrollment')], default='manual', max_length=20),
        ),
    ]
