# Generated by Django 5.2.7 on 2026-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_note_type_alter_note_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profileTypes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
