# Generated by Django 5.2.7 on 2026-04-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_ask_ai_enabled_note_ask_ai_monthly_price_and_more'),
        ('notes', '0003_note_profiletypes'),
    ]

    operations = [
    ]
