# Generated by Codex on 2026-04-25

from copy import deepcopy
from urllib.parse import urlparse

from django.conf import settings
from django.db import migrations


TUTORIAL_CONCEPT_LIBRARY = {
    "number-and-algebra": [
        "Arithmetic and geometric sequences and series",
        "Sigma notation and finite summation techniques",
        "Exponential laws and logarithmic rules",
        "Equation solving with powers and logarithms",
        "Binomial expansion and binomial coefficients",
        "Algebraic rearrangement, factorization, and simplification",
        "Mathematical notation fluency used across IB problem solving",
    ],
    "functions": [
        "Function notation, domain, and range",
        "Graph interpretation using intercepts, symmetry, and end behavior",
        "Transformations including translations, reflections, and stretches",
        "Linear, quadratic, rational, exponential, and logarithmic functions",
        "Inverse functions and composite functions",
        "Equation solving through graphical and algebraic reasoning",
        "Modeling real relationships with functions",
    ],
    "geometry-and-trigonometry": [
        "Coordinate geometry in two dimensions",
        "Distance, midpoint, gradient, and line relationships",
        "Area, volume, and geometric reasoning in 2D and 3D",
        "Sine, cosine, and tangent as ratios and functions",
        "Unit-circle thinking and standard trigonometric graphs",
        "Trigonometric identities and equations",
        "Applications of trigonometry in non-right and contextual problems",
    ],
    "statistics-and-probability": [
        "Data collection, organization, and visual representation",
        "Measures of center and spread",
        "Discrete and continuous probability ideas",
        "Conditional probability and tree or Venn-diagram reasoning",
        "Probability distributions and expected value",
        "Scatter plots, correlation, and regression interpretation",
        "Critical interpretation of statistical conclusions",
    ],
    "calculus": [
        "Limits as the foundation of calculus reasoning",
        "Differentiation rules for algebraic and transcendental functions",
        "Tangents, rates of change, and gradient interpretation",
        "Optimization and motion applications of derivatives",
        "Antiderivatives and definite integrals",
        "Area under curves and accumulation models",
        "Links between graphs, derivatives, and integrals",
    ],
    "data-structures-and-algorithms": [
        "Asymptotic analysis with time and space complexity",
        "Arrays, strings, stacks, queues, linked lists, trees, heaps, and hash maps",
        "Searching, sorting, and recursion",
        "Binary trees, BSTs, heaps, and traversal strategies",
        "Graphs, shortest paths, traversal, and connectivity problems",
        "Dynamic programming, greedy algorithms, and divide-and-conquer",
        "Problem decomposition and correctness reasoning",
    ],
    "web-development": [
        "HTML structure, semantic content, forms, and accessibility basics",
        "CSS selectors, layout, responsive design, and styling systems",
        "JavaScript language fundamentals, DOM updates, and browser APIs",
        "State, component thinking, and UI interactivity in frontend apps",
        "HTTP, REST APIs, authentication, and request/response flow",
        "Backend routing, data persistence, and deployment foundations",
        "Project structure and full-stack integration workflows",
    ],
    "database-systems": [
        "Relational modeling with tables, keys, and constraints",
        "Core SQL operations including SELECT, INSERT, UPDATE, and DELETE",
        "Joins, aggregations, filtering, grouping, and subqueries",
        "Schema design and normalization basics",
        "Transactions, consistency, and data integrity concepts",
        "Views, foreign keys, and window functions",
        "Indexes and practical query performance awareness",
    ],
    "aptitude-and-problem-solving": [
        "Percentages, ratios, averages, and profit-loss reasoning",
        "Time-speed-distance and work-time problems",
        "Permutation, combination, and probability-style aptitude questions",
        "Logical sequencing, coding-decoding, and puzzle structures",
        "Data interpretation using charts and tabular information",
        "Pattern recognition and elimination strategies",
        "Test-taking speed and error-reduction habits",
    ],
    "system-design-foundations": [
        "Clients, servers, APIs, and request flow",
        "Databases, caching, and storage choices",
        "Load balancing, scaling, and fault tolerance basics",
        "Synchronous versus asynchronous processing",
        "Queues, background jobs, and event-driven thinking",
        "Service boundaries and simple distributed-system tradeoffs",
        "Communicating architecture clearly in interviews",
    ],
    "system-design": [
        "Scalability, reliability, and availability goals",
        "Caching, replication, partitioning, and consistency models",
        "Message queues, asynchronous workflows, and backpressure",
        "Load balancing and traffic management",
        "Database tradeoffs across relational and distributed storage",
        "Failure handling, resilience, and graceful degradation",
        "Design communication for interviews and architecture reviews",
    ],
    "cloud-and-devops": [
        "Continuous integration and delivery pipeline fundamentals",
        "Containers, images, and reproducible build environments",
        "Infrastructure automation and environment consistency",
        "Deployment strategies and release safety",
        "Cloud service building blocks for compute, storage, and networking",
        "Observability through logs, metrics, traces, and alerts",
        "Operational feedback loops in DevOps teams",
    ],
    "backend-architecture": [
        "API design and service contract clarity",
        "Domain boundaries and modular backend organization",
        "Data flow design across synchronous and asynchronous layers",
        "Idempotency, retries, and failure-aware workflows",
        "Security, validation, and safe input handling",
        "Operational maintainability and service ownership concerns",
        "Refactoring backend systems for growth and clarity",
    ],
    "ai-engineering": [
        "Prompt design and instruction quality",
        "Retrieval-augmented workflows and grounded answers",
        "Structured outputs and tool-using systems",
        "Evaluation loops for quality and regression detection",
        "Latency, cost, and reliability tradeoffs in production AI",
        "Knowledge retrieval and context management patterns",
        "Safety, hallucination handling, and user trust",
    ],
    "technical-interview-strategy": [
        "Project storytelling with ownership and impact framing",
        "Coding interview structure and communication discipline",
        "System design response structure and tradeoff explanation",
        "Behavioral interview examples using clear narratives",
        "Resume and profile alignment with target roles",
        "Senior-level judgment signals and leadership communication",
        "Interview iteration through feedback and reflection",
    ],
}

MATH_TUTORIAL_SLUGS = {
    "number-and-algebra",
    "functions",
    "geometry-and-trigonometry",
    "statistics-and-probability",
    "calculus",
}

PROGRAMMING_TUTORIAL_SLUGS = {
    "data-structures-and-algorithms",
    "web-development",
    "database-systems",
    "aptitude-and-problem-solving",
    "system-design-foundations",
    "system-design",
    "cloud-and-devops",
    "backend-architecture",
    "ai-engineering",
    "technical-interview-strategy",
}

SEED_DESCRIPTION_MARKER = "Part of the Tutorlix tutorial concept library."


def slugify_value(value):
    value = (value or "").lower()
    value = value.replace("&", " and ")
    cleaned = []
    previous_dash = False
    for char in value:
        if char.isalnum():
            cleaned.append(char)
            previous_dash = False
        else:
            if not previous_dash:
                cleaned.append("-")
                previous_dash = True
    slug = "".join(cleaned).strip("-")
    return slug or "concept"


def sentence_case_list(items):
    cleaned = [item.strip().rstrip(".") for item in items if item and item.strip()]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]} and {cleaned[1]}"
    return f"{', '.join(cleaned[:-1])}, and {cleaned[-1]}"


def first_sentence(text):
    text = (text or "").strip()
    if not text:
        return ""
    for separator in ".!?":
        index = text.find(separator)
        if index != -1:
            return text[: index + 1]
    return text


def fallback_concepts(tutorial_title):
    return [
        f"{tutorial_title} foundations",
        f"Core workflow in {tutorial_title}",
        f"Problem solving with {tutorial_title}",
        f"Common mistakes in {tutorial_title}",
    ]


def normalize_concept_item(concept):
    if isinstance(concept, str):
        title = concept.strip()
        return {
            "slug": slugify_value(title),
            "title": title,
            "noteUrl": "",
        }

    if not isinstance(concept, dict):
        return None

    title = (concept.get("title") or "").strip()
    if not title:
        return None

    normalized = deepcopy(concept)
    normalized["title"] = title
    normalized["slug"] = concept.get("slug") or slugify_value(title)
    normalized["noteUrl"] = concept.get("noteUrl") or ""
    return normalized


def extract_note_slug(note_url):
    if not note_url:
        return None
    parsed = urlparse(note_url)
    segments = [segment for segment in parsed.path.split("/") if segment]
    if "notes" not in segments:
        return None
    index = segments.index("notes")
    if index == len(segments) - 1:
        return None
    return segments[index + 1]


def make_note_slug(tutorial_slug, concept_slug):
    base = f"tutorial-{slugify_value(tutorial_slug)}-{slugify_value(concept_slug)}"
    return base[:240].strip("-")


def make_note_url(note_slug):
    return f"/notes/{note_slug}"


def tutorial_examples(tutorial_slug, concept_title):
    if tutorial_slug in MATH_TUTORIAL_SLUGS:
        return [
            f"Work through a short exam-style problem where {concept_title.lower()} is the main technique and justify every algebraic step.",
            f"Represent {concept_title.lower()} in at least two ways, such as symbolic work plus a graph, table, diagram, or verbal explanation.",
            f"Compare a correct and incorrect solution to show how {concept_title.lower()} changes the final conclusion.",
        ]

    mapping = {
        "data-structures-and-algorithms": [
            f"Trace a small input by hand and record how {concept_title.lower()} affects state changes at each step.",
            f"Write short pseudocode that uses {concept_title.lower()} and then explain its time and space cost.",
            f"Compare two candidate approaches and justify when {concept_title.lower()} is the better engineering choice.",
        ],
        "web-development": [
            f"Build a minimal feature where {concept_title.lower()} appears in the browser, the API layer, and the user experience.",
            f"Explain how {concept_title.lower()} affects maintainability, performance, and accessibility in a small web app.",
            f"Review a simple bug scenario and describe how better use of {concept_title.lower()} would prevent it.",
        ],
        "database-systems": [
            f"Model a tiny schema that demonstrates {concept_title.lower()} and explain the tradeoffs in your table design.",
            f"Write a query or query plan that shows how {concept_title.lower()} improves correctness or performance.",
            f"Describe how bad data assumptions can break results when {concept_title.lower()} is ignored.",
        ],
        "aptitude-and-problem-solving": [
            f"Solve one timed question using {concept_title.lower()} and then rewrite the solution as a repeatable method.",
            f"List the shortcut checks that help you avoid arithmetic traps while working with {concept_title.lower()}.",
            f"Create a second practice question and explain which clues tell you that {concept_title.lower()} is the right approach.",
        ],
        "system-design-foundations": [
            f"Sketch a simple architecture diagram and show where {concept_title.lower()} fits into request flow and system boundaries.",
            f"Explain a small product scenario where {concept_title.lower()} improves reliability or scale.",
            f"Describe one tradeoff you would mention in an internship or entry-level system design discussion about {concept_title.lower()}.",
        ],
        "system-design": [
            f"Design a service at moderate scale and show how {concept_title.lower()} changes reliability, latency, or cost.",
            f"Evaluate a failure scenario and explain how {concept_title.lower()} helps the system degrade gracefully.",
            f"Prepare a short whiteboard explanation that defends your choice of {concept_title.lower()} in a design review.",
        ],
        "cloud-and-devops": [
            f"Describe a delivery pipeline or deployment flow where {concept_title.lower()} reduces operational risk.",
            f"Explain how you would observe, alert on, or roll back a problem related to {concept_title.lower()}.",
            f"Compare a manual workflow with an automated one to show why {concept_title.lower()} matters in production teams.",
        ],
        "backend-architecture": [
            f"Document a backend workflow where {concept_title.lower()} improves clarity between API, domain, and infrastructure layers.",
            f"Review a failure path and explain how {concept_title.lower()} reduces duplicate work or broken state transitions.",
            f"Refactor a small service design to show how {concept_title.lower()} improves maintainability over time.",
        ],
        "ai-engineering": [
            f"Create a lightweight product scenario where {concept_title.lower()} improves answer quality, trust, or operational safety.",
            f"Describe how you would test or evaluate {concept_title.lower()} before shipping an AI feature to users.",
            f"Compare a fast prototype with a production-ready version to show the engineering discipline behind {concept_title.lower()}.",
        ],
        "technical-interview-strategy": [
            f"Draft a concise interview answer where {concept_title.lower()} improves structure, clarity, and confidence.",
            f"Rewrite a weak project explanation into a stronger one by applying {concept_title.lower()}.",
            f"Create a reflection checklist so you can improve {concept_title.lower()} after each mock interview.",
        ],
    }
    return mapping.get(
        tutorial_slug,
        [
            f"Write a short walkthrough showing how {concept_title.lower()} appears in a realistic {tutorial_slug.replace('-', ' ')} scenario.",
            f"Explain how you would teach {concept_title.lower()} to a beginner who has to use it under time pressure.",
            f"Review one weak example and one strong example to highlight good judgment around {concept_title.lower()}.",
        ],
    )


def tutorial_mistakes(tutorial_slug, concept_title):
    if tutorial_slug in MATH_TUTORIAL_SLUGS:
        return [
            f"Using {concept_title.lower()} mechanically without checking the conditions, notation, or meaning of the symbols involved.",
            "Skipping intermediate reasoning and jumping from formula to answer without explaining why the step is valid.",
            "Treating the final value as enough without checking whether it is sensible in the context of the question.",
        ]

    mapping = {
        "data-structures-and-algorithms": [
            "Optimizing before correctness is proven on simple test cases and edge cases.",
            f"Choosing a structure because it is familiar instead of because {concept_title.lower()} is the best fit for the operations required.",
            "Ignoring complexity tradeoffs, invariants, or failure modes while explaining the solution.",
        ],
        "web-development": [
            "Building UI behavior without a clear mental model of state, data flow, and user intent.",
            "Treating APIs, accessibility, and responsiveness as afterthoughts instead of core feature requirements.",
            f"Using {concept_title.lower()} in isolation without considering integration with the rest of the stack.",
        ],
        "database-systems": [
            "Writing queries that seem correct on small data but break on duplicates, nulls, or missing constraints.",
            "Ignoring consistency and transaction boundaries while reasoning about updates.",
            f"Assuming {concept_title.lower()} is only theory instead of a production design decision with real consequences.",
        ],
        "aptitude-and-problem-solving": [
            "Rushing into arithmetic before identifying the governing pattern or relation.",
            "Failing to estimate, cross-check, or eliminate clearly impossible answer choices.",
            f"Practicing {concept_title.lower()} passively instead of turning it into a timed decision rule.",
        ],
        "system-design-foundations": [
            "Listing components without explaining request flow, data flow, or failure behavior.",
            "Using scale vocabulary without tying it to an actual bottleneck or business need.",
            f"Discussing {concept_title.lower()} as jargon instead of as a concrete design decision.",
        ],
        "system-design": [
            "Designing for maximum complexity before clarifying requirements and traffic assumptions.",
            "Ignoring tradeoffs among consistency, latency, resilience, and operational cost.",
            f"Using {concept_title.lower()} as a buzzword rather than defending it with clear reasoning.",
        ],
        "cloud-and-devops": [
            "Treating deployment as a one-time script instead of an observable, repeatable system.",
            "Automating steps without recovery, rollback, or safety checks.",
            f"Applying {concept_title.lower()} without linking it to team velocity and incident response.",
        ],
        "backend-architecture": [
            "Letting endpoints, services, and persistence concerns blur together until ownership becomes unclear.",
            "Handling retries or side effects without idempotency and failure awareness.",
            f"Using {concept_title.lower()} as documentation language but not enforcing it in code and workflows.",
        ],
        "ai-engineering": [
            "Judging AI features only by demos instead of evaluation, guardrails, and user trust.",
            "Ignoring cost, latency, and hallucination behavior while scaling prototypes.",
            f"Relying on {concept_title.lower()} without measuring whether it actually improves product outcomes.",
        ],
        "technical-interview-strategy": [
            "Giving detailed but unstructured answers that hide impact and ownership.",
            "Preparing isolated answers instead of a coherent narrative across resume, behavior, coding, and design rounds.",
            f"Using {concept_title.lower()} inconsistently so strong experiences still sound weaker than they are.",
        ],
    }
    return mapping.get(
        tutorial_slug,
        [
            "Jumping into execution before clarifying assumptions, scope, and success criteria.",
            f"Treating {concept_title.lower()} as a memorized phrase instead of a repeatable reasoning pattern.",
            "Failing to reflect on mistakes and convert them into clearer future habits.",
        ],
    )


def tutorial_practice_prompts(tutorial_slug, concept_title, tutorial_title):
    if tutorial_slug in MATH_TUTORIAL_SLUGS:
        return [
            f"Explain {concept_title.lower()} in your own words without using memorized textbook language.",
            f"Solve one short {tutorial_title.lower()} problem using {concept_title.lower()} and annotate each reasoning step.",
            f"Create a checklist for when {concept_title.lower()} is the right tool and when another method is better.",
        ]

    mapping = {
        "data-structures-and-algorithms": [
            f"Implement a toy example that uses {concept_title.lower()} and write tests for normal, edge, and worst cases.",
            f"Compare {concept_title.lower()} with a weaker alternative and defend your choice in interview style.",
            "Teach the concept out loud as if you were mentoring a junior student during placement prep.",
        ],
        "web-development": [
            f"Build a tiny demo where {concept_title.lower()} improves usability, maintainability, or correctness.",
            "Explain the browser, server, and data-flow implications of your design in one page of notes.",
            "Review a broken interface and list the engineering habits that would prevent the same issue in production.",
        ],
        "database-systems": [
            f"Design a small schema and query set that depends on {concept_title.lower()} to stay correct over time.",
            "Write down the assumptions behind your query logic and test what happens when those assumptions fail.",
            "Explain the tradeoff between easier implementation now and safer data behavior later.",
        ],
        "aptitude-and-problem-solving": [
            f"Create three timed questions where {concept_title.lower()} is the deciding idea, then solve them under a strict clock.",
            "Record the first mistake you make and rewrite the solution method so the mistake becomes less likely next time.",
            "Practice explaining why an answer choice is wrong, not only why the correct choice works.",
        ],
        "system-design-foundations": [
            f"Draw a simple system using {concept_title.lower()} and narrate the request flow from user action to stored result.",
            "Identify one bottleneck, one failure mode, and one simplification in your design.",
            "Practice defending your architecture in under three minutes to build communication clarity.",
        ],
        "system-design": [
            f"Design a realistic service where {concept_title.lower()} is central, then justify your scale assumptions.",
            "List the tradeoffs you accepted deliberately and the alternatives you rejected.",
            "Run a mini design review with yourself: requirements, bottlenecks, failure handling, and operational concerns.",
        ],
        "cloud-and-devops": [
            f"Map a delivery workflow where {concept_title.lower()} shortens feedback loops without reducing safety.",
            "Create an incident scenario and explain how monitoring, rollback, and team process should respond.",
            "Document the operational metrics that would prove your solution is actually working in production.",
        ],
        "backend-architecture": [
            f"Refactor a small service diagram so {concept_title.lower()} is visible in boundaries, data flow, and error handling.",
            "List the contracts between layers and note what can fail at each boundary.",
            "Explain how you would keep the design understandable as the team and codebase grow.",
        ],
        "ai-engineering": [
            f"Design a lightweight experiment to measure whether {concept_title.lower()} improves answer quality for real users.",
            "Write the guardrails, evaluation checks, and fallback behavior you would want before launch.",
            "Compare the prototype mindset with the production mindset for the same AI feature.",
        ],
        "technical-interview-strategy": [
            f"Write a mock interview answer where {concept_title.lower()} improves structure, signal, and confidence.",
            "Review one old interview answer and revise it so ownership, tradeoffs, and impact are easier to hear.",
            "Define the feedback loop you will use after each mock or real interview to improve deliberately.",
        ],
    }
    return mapping.get(
        tutorial_slug,
        [
            f"Write a worked example that applies {concept_title.lower()} to a realistic {tutorial_title.lower()} scenario.",
            "Explain your reasoning out loud and note where your explanation is vague or unsupported.",
            "Turn one weak habit into a concrete checklist item you can use during practice.",
        ],
    )


def build_markdown_note(tutorial_title, tutorial_overview, concept_title, learn_points, tutorial_slug):
    tutorial_sentence = first_sentence(tutorial_overview) or f"{tutorial_title} builds essential understanding through structured practice."
    learn_points_text = sentence_case_list(learn_points[:3])
    if learn_points_text:
        explanation_link = f"It connects directly to the broader tutorial goals of {learn_points_text.lower()}."
    else:
        explanation_link = f"It supports the wider reasoning framework used throughout {tutorial_title}."

    overview_section = (
        f"{concept_title} is a core concept inside **{tutorial_title}**. "
        f"{tutorial_sentence} This note is designed to help a learner understand the idea, apply it with confidence, "
        f"and avoid the most common reasoning mistakes. {explanation_link}"
    )

    explanation_paragraphs = [
        (
            f"Start by defining **{concept_title}** clearly and identifying the objects, variables, structures, or decisions that matter most. "
            f"In strong learning, this concept is never treated as an isolated fact; it becomes useful when you can explain *why* it exists, "
            f"*when* it should be applied, and *what* changes when the inputs or assumptions change."
        ),
        (
            f"A reliable workflow is to represent the situation first, choose the rule or process that matches **{concept_title}**, "
            f"work step by step, and then verify that the result is consistent with the context of **{tutorial_title}**. "
            f"This helps move from memorization to transferable understanding."
        ),
        (
            f"As you revise, connect **{concept_title}** to nearby ideas in the same tutorial. "
            f"That connection is what allows the concept to appear naturally in mixed problems, projects, design discussions, or interview explanations."
        ),
    ]

    key_ideas = [
        f"Define **{concept_title}** precisely before applying any rule, formula, or workflow.",
        f"Identify the standard representation of **{concept_title}** used in **{tutorial_title}**.",
        "Break the task into smaller steps so the reasoning remains visible and checkable.",
        "Test assumptions, constraints, edge cases, or hidden conditions before finalizing the answer.",
        f"Link **{concept_title}** to adjacent ideas so it becomes part of a broader problem-solving toolkit.",
    ]

    examples = tutorial_examples(tutorial_slug, concept_title)
    mistakes = tutorial_mistakes(tutorial_slug, concept_title)
    practice_prompts = tutorial_practice_prompts(tutorial_slug, concept_title, tutorial_title)

    summary_points = [
        f"**{concept_title}** matters because it strengthens how you reason inside **{tutorial_title}**.",
        "Good performance comes from combining definition, representation, method, and verification.",
        "The concept becomes durable when you can explain it, use it, and critique incorrect uses of it.",
    ]

    lines = [
        f"# {concept_title}",
        "",
        "## Overview",
        overview_section,
        "",
        "## Explanation",
    ]
    for paragraph in explanation_paragraphs:
        lines.extend([paragraph, ""])

    lines.append("## Key Ideas")
    lines.extend([f"- {item}" for item in key_ideas])
    lines.extend(["", "## Examples"])
    lines.extend([f"- {item}" for item in examples])
    lines.extend(["", "## Common Mistakes"])
    lines.extend([f"- {item}" for item in mistakes])
    lines.extend(["", "## Summary"])
    lines.extend([f"- {item}" for item in summary_points])
    lines.extend(["", "## Practice Prompts"])
    lines.extend([f"- {item}" for item in practice_prompts])
    lines.append("")
    return "\n".join(lines)


def text_content(text):
    return [{"type": "text", "text": text, "styles": {}}]


def make_block(block_type, text, props=None):
    return {
        "type": block_type,
        "props": props or {},
        "content": text_content(text),
        "children": [],
    }


def markdown_to_blocknote(markdown_text):
    blocks = []
    paragraph_lines = []
    bullet_lines = []

    def flush_paragraph():
        if paragraph_lines:
            text = " ".join(line.strip() for line in paragraph_lines if line.strip())
            if text:
                blocks.append(make_block("paragraph", text))
            paragraph_lines[:] = []

    def flush_bullets():
        if bullet_lines:
            for line in bullet_lines:
                blocks.append(make_block("bulletListItem", line))
            bullet_lines[:] = []

    for raw_line in (markdown_text or "").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if not stripped:
            flush_paragraph()
            flush_bullets()
            continue

        if stripped.startswith("### "):
            flush_paragraph()
            flush_bullets()
            blocks.append(make_block("heading", stripped[4:], {"level": 3}))
            continue

        if stripped.startswith("## "):
            flush_paragraph()
            flush_bullets()
            blocks.append(make_block("heading", stripped[3:], {"level": 2}))
            continue

        if stripped.startswith("# "):
            flush_paragraph()
            flush_bullets()
            blocks.append(make_block("heading", stripped[2:], {"level": 1}))
            continue

        if stripped.startswith("- "):
            flush_paragraph()
            bullet_lines.append(stripped[2:].strip())
            continue

        flush_bullets()
        paragraph_lines.append(stripped)

    flush_paragraph()
    flush_bullets()
    return blocks


def choose_creator(User):
    for role in ("admin", "teacher"):
        user = User.objects.filter(role=role, is_active=True).order_by("id").first()
        if user:
            return user
    return User.objects.filter(is_active=True).order_by("id").first()


def note_payload(Note, creator, tutorial_slug, tutorial_title, concept, tutorial_overview, learn_points, profile_slug):
    concept_slug = concept["slug"]
    note_title = f"{concept['title']} - {tutorial_title}"
    note_slug = make_note_slug(tutorial_slug, concept_slug)
    markdown = build_markdown_note(
        tutorial_title=tutorial_title,
        tutorial_overview=tutorial_overview,
        concept_title=concept["title"],
        learn_points=learn_points,
        tutorial_slug=tutorial_slug,
    )

    payload = {
        "title": note_title,
        "slug": note_slug,
        "content": markdown_to_blocknote(markdown),
        "creator_id": creator.id,
        "note_type": "individual",
        "privacy": "public",
        "price": 0,
        "discounted_price": None,
        "access_duration_days": 0,
        "description": (
            f"Detailed study note for the core concept \"{concept['title']}\" inside {tutorial_title}. "
            f"{SEED_DESCRIPTION_MARKER}"
        ),
        "is_draft": False,
        "is_active": True,
    }

    note_fields = {field.name for field in Note._meta.get_fields() if hasattr(field, "name")}
    if "profileTypes" in note_fields:
        payload["profileTypes"] = [profile_slug]
    if "ask_ai_enabled" in note_fields:
        payload["ask_ai_enabled"] = False
    if "ask_ai_monthly_price" in note_fields:
        payload["ask_ai_monthly_price"] = 0
    return payload, markdown


def get_or_create_note(Note, creator, tutorial_slug, tutorial_title, concept, tutorial_overview, learn_points, profile_slug):
    existing_slug = extract_note_slug(concept.get("noteUrl"))
    if existing_slug:
        existing_note = Note.objects.filter(slug=existing_slug).first()
        if existing_note:
            return existing_note, False

    note_slug = make_note_slug(tutorial_slug, concept["slug"])
    existing_note = Note.objects.filter(slug=note_slug).first()
    if existing_note:
        note_fields = {field.name for field in Note._meta.get_fields() if hasattr(field, "name")}
        if (
            "profileTypes" in note_fields
            and SEED_DESCRIPTION_MARKER in (existing_note.description or "")
        ):
            current_profiles = list(getattr(existing_note, "profileTypes", []) or [])
            if profile_slug not in current_profiles:
                current_profiles.append(profile_slug)
                existing_note.profileTypes = current_profiles
                existing_note.save(update_fields=["profileTypes"])
        return existing_note, False

    if creator is None:
        return None, False

    payload, _markdown = note_payload(
        Note=Note,
        creator=creator,
        tutorial_slug=tutorial_slug,
        tutorial_title=tutorial_title,
        concept=concept,
        tutorial_overview=tutorial_overview,
        learn_points=learn_points,
        profile_slug=profile_slug,
    )
    return Note.objects.create(**payload), True


def ensure_concept_metadata(concept, tutorial_slug, tutorial_title, tutorial_overview, learn_points):
    concept.setdefault("slug", slugify_value(concept["title"]))
    note_title = f"{concept['title']} - {tutorial_title}"
    concept.setdefault("noteTitle", note_title)
    concept.setdefault(
        "noteSummary",
        (
            f"{concept['title']} is a core part of {tutorial_title}. "
            f"This note helps you understand the idea, use it correctly, and connect it to broader reasoning."
        ),
    )
    concept.setdefault(
        "notePoints",
        [
            f"Understand what {concept['title'].lower()} means before trying to apply it mechanically.",
            f"Relate {concept['title'].lower()} to the wider tutorial goal of {tutorial_title.lower()}.",
            "Use worked examples and self-checks to make the reasoning visible.",
            "Review common mistakes so the concept becomes dependable under pressure.",
            "Practice explaining the concept clearly, not just recalling steps.",
        ],
    )
    return concept


def enrich_tutorial_entry(entry, profile_slug, creator, Note):
    tutorial_slug = entry.get("slug") or slugify_value(entry.get("title") or "tutorial")
    tutorial_title = entry.get("title") or tutorial_slug.replace("-", " ").title()
    tutorial_overview = entry.get("overview") or entry.get("shortDescription") or ""
    learn_points = entry.get("learnPoints") if isinstance(entry.get("learnPoints"), list) else []

    existing_concepts = []
    seen = set()
    for raw_concept in entry.get("conceptsCovered", []) if isinstance(entry.get("conceptsCovered"), list) else []:
        normalized = normalize_concept_item(raw_concept)
        if not normalized:
            continue
        key = normalized["slug"]
        if key in seen:
            continue
        ensure_concept_metadata(normalized, tutorial_slug, tutorial_title, tutorial_overview, learn_points)
        existing_concepts.append(normalized)
        seen.add(key)

    canonical_titles = TUTORIAL_CONCEPT_LIBRARY.get(tutorial_slug) or fallback_concepts(tutorial_title)
    for title in canonical_titles:
        concept_slug = slugify_value(title)
        if concept_slug in seen:
            continue
        normalized = {
            "slug": concept_slug,
            "title": title,
            "noteUrl": "",
        }
        ensure_concept_metadata(normalized, tutorial_slug, tutorial_title, tutorial_overview, learn_points)
        existing_concepts.append(normalized)
        seen.add(concept_slug)

    changed = False
    for concept in existing_concepts:
        note, _created = get_or_create_note(
            Note=Note,
            creator=creator,
            tutorial_slug=tutorial_slug,
            tutorial_title=tutorial_title,
            concept=concept,
            tutorial_overview=tutorial_overview,
            learn_points=learn_points,
            profile_slug=profile_slug,
        )
        if note:
            note_url = make_note_url(note.slug)
            if concept.get("noteUrl") != note_url:
                concept["noteUrl"] = note_url
                changed = True

        ensure_concept_metadata(concept, tutorial_slug, tutorial_title, tutorial_overview, learn_points)

    if entry.get("conceptsCovered") != existing_concepts:
        entry["conceptsCovered"] = existing_concepts
        changed = True

    return changed


def seed_tutorial_core_concepts(apps, schema_editor):
    ProfileType = apps.get_model("lms", "ProfileType")
    Note = apps.get_model("notes", "Note")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    creator = choose_creator(User)

    for profile in ProfileType.objects.all().order_by("id"):
        home_content = deepcopy(profile.home_content or {})
        tutorials = home_content.get("tutorials")
        if not isinstance(tutorials, list) or not tutorials:
            continue

        changed = False
        for tutorial in tutorials:
            if not isinstance(tutorial, dict):
                continue

            pages = tutorial.get("pages")
            if isinstance(pages, list) and pages:
                for page in pages:
                    if isinstance(page, dict):
                        changed = enrich_tutorial_entry(page, profile.slug, creator, Note) or changed
            else:
                changed = enrich_tutorial_entry(tutorial, profile.slug, creator, Note) or changed

        if changed:
            ProfileType.objects.filter(pk=profile.pk).update(home_content=home_content)


def unseed_tutorial_core_concepts(apps, schema_editor):
    ProfileType = apps.get_model("lms", "ProfileType")
    Note = apps.get_model("notes", "Note")
    generated_note_slugs = set(
        Note.objects.filter(description__contains=SEED_DESCRIPTION_MARKER).values_list("slug", flat=True)
    )

    # Clear note links that point at migration-created slugs, but keep the concept entries.
    for profile in ProfileType.objects.all().order_by("id"):
        home_content = deepcopy(profile.home_content or {})
        tutorials = home_content.get("tutorials")
        if not isinstance(tutorials, list) or not tutorials:
            continue

        changed = False
        for tutorial in tutorials:
            if not isinstance(tutorial, dict):
                continue

            page_entries = tutorial.get("pages") if isinstance(tutorial.get("pages"), list) else [tutorial]
            for page in page_entries:
                concepts = page.get("conceptsCovered")
                if not isinstance(concepts, list):
                    continue
                for concept in concepts:
                    if not isinstance(concept, dict):
                        continue
                    note_slug = extract_note_slug(concept.get("noteUrl"))
                    if note_slug in generated_note_slugs:
                        concept["noteUrl"] = ""
                        changed = True

        if changed:
            ProfileType.objects.filter(pk=profile.pk).update(home_content=home_content)

    Note.objects.filter(
        description__contains=SEED_DESCRIPTION_MARKER,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lms", "0042_merge_20260425_1418"),
        ("notes", "0005_ensure_note_profiletypes_column"),
    ]

    operations = [
        # Enrich persisted tutorial JSON with concept entries and attach public notes
        # without touching schema, views, serializers, or routes.
        migrations.RunPython(seed_tutorial_core_concepts, unseed_tutorial_core_concepts),
    ]
