# Generated by Codex on 2026-04-25

from django.db import migrations


def blocknote_text_content(text):
    return [{"type": "text", "text": text, "styles": {}}]


def blocknote_heading_block(title):
    return {
        "type": "heading",
        "props": {"level": 1},
        "content": blocknote_text_content(title),
        "children": [],
    }


def extract_block_text(block):
    content = block.get("content")
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""

    parts = []
    for item in content:
        if isinstance(item, dict):
            text = item.get("text")
            if isinstance(text, str) and text.strip():
                parts.append(text.strip())
        elif isinstance(item, str) and item.strip():
            parts.append(item.strip())
    return " ".join(parts).strip()


def ensure_title_heading(content, title):
    title = (title or "").strip()
    if not title:
        return content

    blocks = list(content) if isinstance(content, list) else []

    def is_matching_title_heading(block):
        if not isinstance(block, dict):
            return False
        if block.get("type") != "heading":
            return False
        props = block.get("props") or {}
        if props.get("level") != 1:
            return False
        return extract_block_text(block).casefold() == title.casefold()

    for index, block in enumerate(blocks):
        if is_matching_title_heading(block):
            if index == 0:
                return blocks
            return [block, *blocks[:index], *blocks[index + 1:]]

    return [blocknote_heading_block(title), *blocks]


def backfill_note_title_headings(apps, schema_editor):
    Note = apps.get_model("notes", "Note")

    for note in Note.objects.only("id", "title", "content").iterator():
        normalized_content = ensure_title_heading(note.content, note.title)
        if normalized_content != note.content:
            Note.objects.filter(pk=note.pk).update(content=normalized_content)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_seed_tutorial_core_concept_notes"),
    ]

    operations = [
        migrations.RunPython(backfill_note_title_headings, migrations.RunPython.noop),
    ]
